charter/index.html
proposed starting point for WebVR specific charter content.
=> [charter]proposed initial content

charter/index.html
Added headings in scope section to make it clearer what specs the paragraphs apply to.  Currently it isn't clear when the intro to the specs start.
=> Added headings in scope section

charter/index.html
We have better information now on what the proposed API is.
=> added description of the hand position api

LICENSE.md
=> edit to LICENSE.md for test suites

Makefile, index.bs, index.html
In order to get bikeshed to build this had to list it under an existing group. Chose html. Not technically correct, but gets us working again.
=> Update index.bs to resolve errors/warnings

index.bs
@kearwood is this what you meant?
=> Specifies the type of matrix returned by sittingToStandingTransform

index.bs, index.html
Trying to capture https://github.com/w3c/webvr/issues/72 opened by @kearwood
=> requestPresent throws an Error when VRLayers source is null (fix #72)

index.bs, index.html
Captures changes proposed in https://github.com/w3c/webvr/issues/67
=> Describe null value for VRDevice.stageParameters attribute

index.bs, index.html
It tries to capture conversation in https://github.com/w3c/webvr/issues/68
=> Timestamp value is specific to each VRDisplay (fix #68)

index.bs
=> Add requested reason to VRDisplayEventReason fix #106

index.bs, index.html
requestPresent now accepts an array of VRLayerInit dictionaries.
getLayers returns an array of VRLayers. Fixes #107
Also included some random bikeshed error fixes.
=> Convert VRLayer to an interface

Makefile, archive/index.html, archive/prerelease/1.1/index.bs, archive/prerelease/1.1/index.html, archive/style.css
Sets up a folder to retain older versions of the spec in for reference.
=> Archive for previous versions of the spec

archive/prerelease/1.1/index.bs, archive/prerelease/1.1/index.html, index.bs, index.html
Removing based on discussion in #25
=> Removed allowvr from 1.1 and 1.2 versions of the spec.

explainer.md
Moves `getViewport` from `VRPresentationFrame` to `VRView` and changes
`VRWebGLViewport` to `VRViewport`. Fixes #231.
Given that there hasn't been any negative feedback on #231 I'll leave this open for comments for a day or two and then merge if there's no outstanding concerns.
=> Revise getViewport behavior

explainer.md
Given the recent changes in the render loop there no longer seems to be
a reason to track the canvas itself, so I propose here switching the
VRWebGLLayer to accept the rendering context instead.
Also did some research and found that, as @kenrussell warned, we can’t use
WebGLRenderingContextBase in our IDL directly. So instead we get to
play with more typedefs! *sigh*
=> Change VRWebGLLayer to take a context rather than a canvas

explainer.md
While talking with @NellWaliczek today she pointed out that Microsoft
was concerned about how to deal with VRPresentationFrame promises that
the app holds a reference to and calls `.then()` on well after the
frame has been processed. Upon reflection this is definitely a sticky
problem: Ideally we want any frame callbacks registered to simply pick
up the next frame’s data, but with a promise you could effectively hold
onto a stale frame for a long time.
It could be made to work, but the spec gymnastics required to ensure
sensible behavior would be significant and hard to parse, while the
existing `requestAnimationFrame` syntax is already well understood by
devs and gives us the desired behavior of never being able to fire a
frame callback for a stale frame. It will require a bit of …
=> Change animation loop from promise-based to callback-based

explainer.md
The need to make this more explicit was identified by discussion around #236.
=> Clarify the definitions and uses of "suspended" vs. "ended" sessions

explainer.md
=> Fix a typo

explainer.md
Fixes #262.
Posting as a pull request to allow for comments before merging.
=> Make "exclusive" session creation argument false by default

README.md
per https://github.com/w3c/gamepad/pull/64/files#r146330440
=> add `Tests` section to README (for `w3c/web-platform-tests`)

explainer.html, explainer.md, spec/latest/index.bs, spec/latest/index.html
Discussed this previously in #317. This feels better scoped to me,
since not every layer will need viewports (or may not need different
viewports per view.)
=> Moved `getViewport` from `XRView` to `XRWebGLLayer`

explainer.md
Pull request based on the latest conversation from #319 and the WebXR CG call.
I said I would have this out by end of day, which is now technically correct. ;) I expect that I've missed all sorts of dumb typos in my push to get this out before I fall asleep tonight, though. My apologies in advance.
=> Add Basic Input description to the explainer

explainer.md
Not much to say about this one. Resolves longstanding issue #120. Inclined to push this soon if there's no comments about it. The only possible concern I could see others having is the specification that changes to the depth values take effect on the next frame.
=> Add text explaining the depth range values.

explainer.md
As discussed in #364 and confirmed on today's WebXR call.
'exclusive' -> 'immersive'
This change involves a bit more modification of the explainer text throughout (I have not included `index.bs` changed in this PR) so I'll leave it up for a few days prior to merging just incase anyone sees something that needs correction.
=> Renamed exclusive->immersive

explainer.md
There's a lot more to unpack here than the size of the diff would suggest, so let me explain some of the intentions behind this.
First off, this definitely will need to be rebased on top of #342, but I'm happy to do that after it's landed. In the meantime I've adopted the name of the ray that is present in that change. (`targetRay` instead of `pointerRay`).
Second, I should point out that the `transformMatrix` given on the ray is intended as a developer convenience, since that's what you'll frequently need to render with. It is not intended to be supplied or modified by the developer, and would be lazily computed when first queried. Since it's effectively syntactic sugar we could easily drop it, but I rather like it.
This change is designed not only to make the target ray case nicer but …
=> Created an explicit XRRay type

index.bs
Described in the explainer, but not in the spec text
=> Add XRSession inputsourceschange event

README.md
* Add section on getting started since this is a likely location new participants will want to look
* Remove (inactive?) slack channel
* "Legacy" Gamepad Extensions
* WebVR CG -> Immersive Web CG
=> Update readme for the creation of the WG

CODE_OF_CONDUCT.md, CONTRIBUTING.md, LICENSE.md, README.md, w3c.json
w3c.json per https://w3c.github.io/w3c.json.html
LICENSE and CONTRIBUTING files aligned with templates at https://github.com/w3c/licenses/
Using CODE_OF_CONDUCT.md per github convention https://help.github.com/articles/adding-a-code-of-conduct-to-your-project/
=> Align repo administrative files with operations under the IWWG umbrella

explainer.md
Based on some of the discussion in #317, the WebXR calls, and the WebGL face-to-face meetings, it appears that doing multiview rendering with the standard opaque framebuffer isn't going to work out. Instead, we'd like to make use of as many of the existing features of WebGL 2 as possible to align with the native multiview extension functionality.
I'm approaching this in two steps. First, in this pull request, I'm removing the multiview concept from the `XRWebGLLayer`. That's pretty straightforward.
The next step, then, would be to introduce a WebGL 2-only layer type that provides texture arrays instead of the opaque framebuffer. I'm not sure if that's something that we want to do in v1 release, though. My gut says no? For the sake of tracking where we'd like to go, however, I've written …
=> Removed multiview attribute from XRWebGLLayer

index.bs
Focused here primarily on getting the IDL and algorithms updated. There's a fair amount of new text that probably should be added to cover what, exactly, "immersive-ar" mode implies but I'm deferring that work for the moment.
Also threw in a few additional fixes like warning corrections for the bikeshed `make` process and the odd spelling error that I stumbled on.
=> Updated spec with XRSessionMode changes

index.bs
I think this is a spelling mistake.
=> s/in not/is not/

explainer.md, index.bs
Also fixed a minor inconsistency in the explainer regarding the name of the associated dictionary.
=> Add XRRenderState to the spec

input-explainer.md
While working on the proposal for adding hit testing to WebXR, it became clear that to easily explain the new hit testing concepts, the input explainer needed a bit of house keeping. I ended up moving a large portion of the document content around, so it may be easier to just view the new version of the document rather than the diff.
The intent with this PR is to clarify the descriptions of existing functionality, not to introduce changes in that functionality. That said, I expect we may uncover shared misunderstandings through the cleaner text, so please do call out things that don't match your expectations. I also removed the grab-and-drag sample code for the moment; it makes a reappearance in the hit-testing-explainer in PR #493
For ease of diffing, the base for this PR is …
=> Restructures input-explainer.md to improve clarity and prep for hit-testing proposal

index.bs
fixes https://github.com/immersive-web/webxr/issues/449
r? @toji
=> Spec XRPresentationContext creation

index.bs
Put in placeholders for definitions which refer to their Github issue.
=> Remove all Bikeshed issues

explainer.md
minor suggestion.  Added a few AR device examples to the list of VR device examples.
=> added a few AR device examples

index.bs
=> Spec: Stationary subtype support is all-or-nothing

explainer.md
Just pushing a small typo while I'm reading, so it's not bound up in future PRs
=> small typo

input-explainer.md
This is a proposal for how we might use the existing Gamepad API to expose controller button and axis state.
=> Gamepad-based button/axis state

explainer.md, index.bs
=> Add none variant to XREye

index.bs
=> Explicitly spec out when requestReferenceSpace() can reject queries

index.bs
replace the outdated (but redirected) webvr repo link
=> Use updated link for explainer

index.bs
=> Add [SameObject] to XRSession.inputSources

index.bs
Implements Option 2 from https://github.com/immersive-web/webxr/issues/630#issuecomment-495781562
fixes #630
=> Handle detached arrays

index.bs
fixes https://github.com/immersive-web/webxr/issues/644
cc @ddorwin
r? @toji
=> Use TAG recommendations for returning promises

index.bs
fixes https://github.com/immersive-web/webxr/issues/677
=> Some XRRenderState clarifications

explainer.md, index.bs
This is a redo of #699 since I made some mistakes in that one I am not sure how to fix.
I think it addressed the comments on that PR
=> Second try @ Remove context Attribute from XRWebGLLayer 

index.bs
Fixes https://github.com/immersive-web/webxr/issues/643
cc @ddorwin
=> Move racy parts of requestSession() to the main thread

index.bs
fixes https://github.com/immersive-web/webxr/issues/484
(I just used @kearwood's suggested language there, seemed good enough)
=> Remove references to swap chain

index.bs
Potential fix for https://github.com/immersive-web/webxr/issues/467
Not quite sure of this, also not sure of what precisely we should list in the platform specific steps.
=> Merge 'end the session' with 'shut down the session', clarify, add onend event

index.bs
fixes https://github.com/immersive-web/webxr/issues/607
=> Don't check XR compat flag for inline sessions

index.bs
Fix algorithm for obtaining XRRay.matrix - copy-paste error introduced by PR #684.
=> Fix detached array in XRRay.matrix algorithm

index.bs
Thanks to @alcooper91 for pointing out the oversight on my part!
=> Removed an outdated gamepad issue reference

index.bs
=> editorial fix on bikeshed and spell

index.bs
fixes https://github.com/immersive-web/webxr/issues/769
=> Forbid using stale XRViews in getViewport()

index.bs
Fixes https://github.com/immersive-web/webxr/issues/481
Most of what we need is already there, but added a bit of text about what the compositor can do, and emphasized that it should protect rendered content from leaking across pages.
=> Clarify the compositor a bit

index.bs
fixes https://github.com/immersive-web/webxr/issues/413
cc @ddorwin
=> Require UAs to show manual device activation steps

index.bs
fixes https://github.com/immersive-web/webxr/issues/676
cc @ddorwin
=> Provide descriptions for each method

index.bs
fixes https://github.com/immersive-web/webxr/issues/711
This ended up being a bit trickier than I thought; I can also do the very simple fix originally proposed.
cc @ddorwin
=> Link to 'fire an input source' algorithm, explicitly construct frame

index.bs
Fixes #778
cc @asajeffrey
r? @toji
=> Ensure an immersive device is selected in makeXRCompatible()

index.bs
=> as 2019/10/07 WD

index.bs
=> Miscellaneous fixes to the XR device definition

index.bs
=> Add a link to the Gamepads module

index.bs
Makes it easier to refer to from the gamepads module
r? @toji
=> Export a dfn for input-source-change

explainer.md
/fixes #826 
Shuffles the surrounding text a bit too to help it flow with the new sample code.
=> Add sample demonstrating context loss handling

index.bs
=> Fix spec to match webidl in explainer for xrCompatible attribute

explainer.md, index.bs
=> Add NewObject attribute to makeXRCompatible

privacy-security-explainer.md
I didn't really capture anything from #696 based on @toji's recent comments.
Happy to add more information if anyone has suggestions
=> summarized #696 (no spec enforced relationship) and #724 for focus/vis

.pr-preview.json
It will avoid to have PR author sending rendered output as in https://github.com/immersive-web/webxr/pull/900
=> Update .pr-preview.json to use the right index.bs

index.bs
Fixed a minor grammar error that I couldn't not fix as it stared at me with hate in its loathsome eyes...
=> Fix grammar error

index.bs
Now uses `await` and `const` consistently where appropriate.
=> Updated remaining code samples 

index.bs
=> Fix syntax for XRPermissionStatus

index.bs
=> Clarified the behavior of visiblityState for inline sessions

index.bs
=> Specify that preserveDrawingBuffer has no power here.

index.bs
=> Add common sense restrictions on viewport shape.

index.bs
WIP.
Accommodates some of the mitigation strategies discussed in #983, but does not resolve that issue.
=> Allow more flexibility in what isSessionSupported returns.

index.bs, spatial-tracking-explainer.md
=> Make XRReferenceSpaceInit.transform nullable

index.bs
=> Documented the effects of the framebufferScaleFactor

index.bs
=> Add self as editor

index.bs
=> Fix use of [=context object=]

index.bs
Fixes #994
may also address https://github.com/immersive-web/webxr/issues/860
cc @kearwood
r? @toji
=> Handle null features and features with stringifiers

index.bs
This is a leftover from an older draft of my permissions changes.
Fixes #1011
r? @toji
=> Session feature requests no longer need the session parameter

index.bs
Fixes #1013
***
<a href="https://pr-preview.s3.amazonaws.com/Manishearth/webxr/pull/1016.html" title="Last updated on May 1, 2020, 6:15 PM UTC (e37a6e5)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/immersive-web/webxr/1016/86839d2...Manishearth:e37a6e5.html" title="Last updated on May 1, 2020, 6:15 PM UTC (e37a6e5)">Diff</a>
=> Add non-normative note about view orientations

index.bs
Fixes https://github.com/immersive-web/webxr/issues/1014
***
<a href="https://pr-preview.s3.amazonaws.com/Manishearth/webxr/pull/1025.html" title="Last updated on May 11, 2020, 9:03 PM UTC (662c467)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/immersive-web/webxr/1025/a64a328...Manishearth:662c467.html" title="Last updated on May 11, 2020, 9:03 PM UTC (662c467)">Diff</a>
=> Discourage xrCompatible where unnecessary

index.bs
Thank you, @nellwaliczek, for all you've done for the immersive web!
***
<a href="https://pr-preview.s3.amazonaws.com/immersive-web/webxr/pull/1039.html" title="Last updated on May 13, 2020, 4:30 PM UTC (648beca)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/immersive-web/webxr/1039/3b2af3e...648beca.html" title="Last updated on May 13, 2020, 4:30 PM UTC (648beca)">Diff</a>
=> Mark Nell as a Former Editor

index.bs
Closes #1040
***
<a href="https://pr-preview.s3.amazonaws.com/cabanier/webxr-1/pull/1043.html" title="Last updated on May 15, 2020, 8:51 PM UTC (7f1e916)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/immersive-web/webxr/1043/dc36a92...cabanier:7f1e916.html" title="Last updated on May 15, 2020, 8:51 PM UTC (7f1e916)">Diff</a>
=> Added validation for XRRigidTransform

index.bs
Thanks everyone for responding!
***
<a href="https://pr-preview.s3.amazonaws.com/immersive-web/webxr/pull/1055.html" title="Last updated on May 20, 2020, 7:56 PM UTC (cf4cb4e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/immersive-web/webxr/1055/d8ae670...cf4cb4e.html" title="Last updated on May 20, 2020, 7:56 PM UTC (cf4cb4e)">Diff</a>
=> First batch of new acknowledgements

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/immersive-web/webxr/pull/1065.html" title="Last updated on May 28, 2020, 5:24 PM UTC (b8c666e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/immersive-web/webxr/1065/a3e80a4...b8c666e.html" title="Last updated on May 28, 2020, 5:24 PM UTC (b8c666e)">Diff</a>
=> Two new names for the acknowledgments

index.bs
Fixes #674
Alternate to #1068
***
<a href="https://pr-preview.s3.amazonaws.com/Manishearth/webxr/pull/1070.html" title="Last updated on May 29, 2020, 4:20 PM UTC (17d0194)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/immersive-web/webxr/1070/403f2e5...Manishearth:17d0194.html" title="Last updated on May 29, 2020, 4:20 PM UTC (17d0194)">Diff</a>
=> Add note about waiting for tracking to be established in requestReferenceSpace()

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/immersive-web/webxr/pull/1075.html" title="Last updated on Jun 4, 2020, 6:19 PM UTC (df5ec12)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/immersive-web/webxr/1075/bedef88...df5ec12.html" title="Last updated on Jun 4, 2020, 6:19 PM UTC (df5ec12)">Diff</a>
=> Add Leonard Daly to acknowledgements

index.bs
=> Bikeshed cleanups

index.bs
=> Allow clamping framebufferScaleFactor

index.bs
Needed for correct cross referencing
=> Fix reference

index.bs
Fixes https://github.com/immersive-web/webxr/issues/913
We no longer awkwardly patch the WebGL spec
***
<a href="https://pr-preview.s3.amazonaws.com/Manishearth/webxr/pull/1097.html" title="Last updated on Jul 6, 2020, 9:13 PM UTC (5ed57d2)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/immersive-web/webxr/1097/d01049d...Manishearth:5ed57d2.html" title="Last updated on Jul 6, 2020, 9:13 PM UTC (5ed57d2)">Diff</a>
=> Correctly handle context loss in makeXRCompatible()

index.bs
Fixes https://github.com/immersive-web/webxr/issues/1103
cc @thetuvix
***
<a href="https://pr-preview.s3.amazonaws.com/Manishearth/webxr/pull/1105.html" title="Last updated on Jul 24, 2020, 1:36 AM UTC (8518b9a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/immersive-web/webxr/1105/de753da...Manishearth:8518b9a.html" title="Last updated on Jul 24, 2020, 1:36 AM UTC (8518b9a)">Diff</a>
=> Primary views MUST always be active

index.bs
(sorry that I forgot this...)
***
<a href="https://pr-preview.s3.amazonaws.com/himorin/webxr/pull/1113.html" title="Last updated on Aug 11, 2020, 2:49 PM UTC (307d41d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/immersive-web/webxr/1113/2cd6a63...himorin:307d41d.html" title="Last updated on Aug 11, 2020, 2:49 PM UTC (307d41d)">Diff</a>
=> updated previous version to WD2020/07/24

index.bs
Fixes https://github.com/immersive-web/webxr/issues/1110
***
<a href="https://pr-preview.s3.amazonaws.com/Manishearth/webxr/pull/1112.html" title="Last updated on Aug 7, 2020, 11:21 PM UTC (efdc41f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/immersive-web/webxr/1112/de753da...Manishearth:efdc41f.html" title="Last updated on Aug 7, 2020, 11:21 PM UTC (efdc41f)">Diff</a>
=> Feature policy -> Permissions policy

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/svillar/webxr/pull/1119.html" title="Last updated on Aug 20, 2020, 4:40 PM UTC (1a3bebe)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/immersive-web/webxr/1119/8276a5c...svillar:1a3bebe.html" title="Last updated on Aug 20, 2020, 4:40 PM UTC (1a3bebe)">Diff</a>
=> Fix view/active reference

index.bs
Some improvements to https://github.com/immersive-web/webxr/pull/1124
This is based on https://github.com/immersive-web/webxr/pull/1124 and is intended to be merged onto that branch
***
<a href="https://pr-preview.s3.amazonaws.com/Manishearth/webxr/pull/1133.html" title="Last updated on Sep 28, 2020, 5:00 PM UTC (c31c223)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/immersive-web/webxr/1133/8c136d3...Manishearth:c31c223.html" title="Last updated on Sep 28, 2020, 5:00 PM UTC (c31c223)">Diff</a>
=> Improvements to the fingerprinting PR

explainer.md
Add a new section explaining dynamic viewport scaling, cf. https://github.com/immersive-web/webxr/issues/1091 and the recent spec addition.
Also add an example showing how framebufferScaleFactor can be changed during a session using a new baseLayer, and clarify the intended scenarios for this vs. dynamic viewport scaling.
=> add dynamic viewport scaling and baseLayer resize example

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/Manishearth/webxr/pull/1136.html" title="Last updated on Oct 9, 2020, 3:41 PM UTC (9437a59)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/immersive-web/webxr/1136/c55ae19...Manishearth:9437a59.html" title="Last updated on Oct 9, 2020, 3:41 PM UTC (9437a59)">Diff</a>
=> Switch isSessionSupported from using user intent to using permissions

README.md
=> Add short info for layers and hand input

index.bs
(copy from webxr-hand-input)
***
<a href="https://pr-preview.s3.amazonaws.com/himorin/webxr/pull/1142.html" title="Last updated on Oct 26, 2020, 12:12 PM UTC (251508a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/immersive-web/webxr/1142/05e33a4...himorin:251508a.html" title="Last updated on Oct 26, 2020, 12:12 PM UTC (251508a)">Diff</a>
=> fixed editor line of Manish

webvr-migration.md
Just fixing a couple of mistakes that might trip up anyone using the webvr migration guide code snippets.
=> Fixes in webvr-migration.md

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/Manishearth/webxr/pull/1145.html" title="Last updated on Nov 18, 2020, 9:10 PM UTC (7cc2088)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/immersive-web/webxr/1145/e453e75...Manishearth:7cc2088.html" title="Last updated on Nov 18, 2020, 9:10 PM UTC (7cc2088)">Diff</a>
=> Fix formatting for fingerprinting constraints

index.bs
This is taken from the discussion in:
https://github.com/immersive-web/webxr/issues/815
=> Added a definition of XR device that includes nonvisual usage

explainer.md
This is a temporary fix for:
https://github.com/immersive-web/webxr/issues/390
and was also discussed in:
https://github.com/immersive-web/webxr/issues/815
=> Added an example of how to connect WebXR Pos with AudioContext.listener Pos

input-explainer.md
Spotted a typo while reading through documentation
=> Fixed a typo in the input explainer

.github/workflows/deploy.yml
=> Fixed GHActions module version

index.bs
Closes #1186
***
<a href="https://pr-preview.s3.amazonaws.com/cabanier/webxr/pull/1188.html" title="Last updated on Mar 29, 2021, 5:56 PM UTC (9d8cdc8)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/immersive-web/webxr/1188/4125a66...cabanier:9d8cdc8.html" title="Last updated on Mar 29, 2021, 5:56 PM UTC (9d8cdc8)">Diff</a>
=> enhance examples of implicit user intent

index.bs
Closes #1193
***
<a href="https://pr-preview.s3.amazonaws.com/cabanier/webxr/pull/1201.html" title="Last updated on Jul 20, 2021, 11:58 PM UTC (12a16fe)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/immersive-web/webxr/1201/cbd417a...cabanier:12a16fe.html" title="Last updated on Jul 20, 2021, 11:58 PM UTC (12a16fe)">Diff</a>
=> Add support for targetFrameRate and supportedFrameRates

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/cabanier/webxr/pull/1215.html" title="Last updated on Jul 23, 2021, 7:39 PM UTC (defa1c8)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/immersive-web/webxr/1215/75fdd84...cabanier:defa1c8.html" title="Last updated on Jul 23, 2021, 7:39 PM UTC (defa1c8)">Diff</a>
=> Add Rik as an editor

index.bs
seems no auto handling by bikeshed...?
***
<a href="https://pr-preview.s3.amazonaws.com/himorin/webxr/pull/1220.html" title="Last updated on Aug 25, 2021, 8:04 AM UTC (6f6c590)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/immersive-web/webxr/1220/42d7489...himorin:6f6c590.html" title="Last updated on Aug 25, 2021, 8:04 AM UTC (6f6c590)">Diff</a>
=> Update previous version per post-WD 2021/08/24

index.bs
(could someone approve this and merge? - for trial of auto-publish to /TR/)
***
<a href="https://pr-preview.s3.amazonaws.com/himorin/webxr/pull/1226.html" title="Last updated on Sep 27, 2021, 4:29 PM UTC (1c69e90)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/immersive-web/webxr/1226/53486c3...himorin:1c69e90.html" title="Last updated on Sep 27, 2021, 4:29 PM UTC (1c69e90)">Diff</a>
=> updated to remove previous version from ED

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/himorin/webxr/pull/1250.html" title="Last updated on Feb 7, 2022, 7:38 AM UTC (a09cea7)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/immersive-web/webxr/1250/74dff44...himorin:a09cea7.html" title="Last updated on Feb 7, 2022, 7:38 AM UTC (a09cea7)">Diff</a>
=> [Editorial] webidl to whatwg

index.bs
- change github.io links to /TR/
- corrected (possible) broken fragments
***
<a href="https://pr-preview.s3.amazonaws.com/himorin/webxr/pull/1251.html" title="Last updated on Feb 8, 2022, 9:15 PM UTC (b22c89b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/immersive-web/webxr/1251/c6a4b0f...himorin:b22c89b.html" title="Last updated on Feb 8, 2022, 9:15 PM UTC (b22c89b)">Diff</a>
=> updated citation and links (per link checker results)

index.bs
We don't actually need to reference this spec, we just need a convenient location to place this algorithm.
Fixes #1262
***
<a href="https://pr-preview.s3.amazonaws.com/Manishearth/webxr/pull/1263.html" title="Last updated on Mar 28, 2022, 2:36 PM UTC (2b0a632)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/immersive-web/webxr/1263/fd8f27d...Manishearth:2b0a632.html" title="Last updated on Mar 28, 2022, 2:36 PM UTC (2b0a632)">Diff</a>
=> Remove permissions-request reference

.github/workflows/auto-publish.yml, index.bs
for streamlined publication after publication of CR.
***
<a href="https://pr-preview.s3.amazonaws.com/himorin/webxr/pull/1259.html" title="Last updated on Mar 31, 2022, 10:32 AM UTC (5dd34e8)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/immersive-web/webxr/1259/692e000...himorin:5dd34e8.html" title="Last updated on Mar 31, 2022, 10:32 AM UTC (5dd34e8)">Diff</a>
=> [DO NOT MERGE NOW] updated GHAction from WD to CRD

index.bs
lines added for upcoming 2022/03/29 CR publication
***
<a href="https://pr-preview.s3.amazonaws.com/immersive-web/webxr/pull/1261.html" title="Last updated on Apr 1, 2022, 6:22 AM UTC (fa48ada)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/immersive-web/webxr/1261/66f8949...fa48ada.html" title="Last updated on Apr 1, 2022, 6:22 AM UTC (fa48ada)">Diff</a>
=> [WIP] material used for 2022/03/29 CR publication

index.bs
Congrats to all of the WebXR Device API editors on reaching Candidate Recommendation 🥳🎉
Better late than never on adding in two missing folks from Microsoft who have contributed to spec issues and PRs for years.
Onward to Proposed Recommendation!
***
<a href="https://pr-preview.s3.amazonaws.com/thetuvix/webxr/pull/1280.html" title="Last updated on Apr 22, 2022, 6:25 PM UTC (2a8ed9a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/immersive-web/webxr/1280/b919cdb...thetuvix:2a8ed9a.html" title="Last updated on Apr 22, 2022, 6:25 PM UTC (2a8ed9a)">Diff</a>
=> Added missing Microsoft acknowledgments

index.bs
see https://dom.spec.whatwg.org/#firing-events
***
<a href="https://pr-preview.s3.amazonaws.com/dontcallmedom/webvr/pull/1288.html" title="Last updated on May 26, 2022, 1:48 PM UTC (08a2bb7)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/immersive-web/webxr/1288/dcaf29d...dontcallmedom:08a2bb7.html" title="Last updated on May 26, 2022, 1:48 PM UTC (08a2bb7)">Diff</a>
=> Use DOM-recommended phrasing for describing events firing

explainer.md
Rename oculus, rift to meta, quest
=> Update Oculus to Meta Quest

index.bs, spatial-tracking-explainer.md
=> moving updates at master

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/cabanier/webxr/pull/1314.html" title="Last updated on Mar 3, 2023, 2:18 AM UTC (bbfdf9a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/immersive-web/webxr/1314/1fb14e7...cabanier:bbfdf9a.html" title="Last updated on Mar 3, 2023, 2:18 AM UTC (bbfdf9a)">Diff</a>
=> Add support for the isSystemKeyboardSupported attribute

index.bs
Addresses #1377 
/tpac
***
<a href="https://pr-preview.s3.amazonaws.com/cabanier/webxr/pull/1392.html" title="Last updated on Sep 23, 2024, 4:48 PM UTC (b5ff587)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/immersive-web/webxr/1392/67d74cd...cabanier:b5ff587.html" title="Last updated on Sep 23, 2024, 4:48 PM UTC (b5ff587)">Diff</a>
=> Add language to account for empty transform in XRReferenceSpaceEvent

index.bs
Fixes #1388
***
<a href="https://pr-preview.s3.amazonaws.com/immersive-web/webxr/pull/1394.html" title="Last updated on Sep 24, 2024, 5:02 PM UTC (9dd27eb)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/immersive-web/webxr/1394/18a5787...9dd27eb.html" title="Last updated on Sep 24, 2024, 5:02 PM UTC (9dd27eb)">Diff</a>
=> Indent section 13.9 to be part of 13.8
