charter/index.html
"to be specific, it's Firefox Nightly release channel and experimental builds of Chromium." from @cvan - I changed the text for that, but it somehow got lost in the previous patch so doing it again.
=> adding fix from @cvan comment

charter/index.html
remove boilerplate language and say the group may produce test suites and refer to the LICENSE file for contribution licensing information. #53 #54
=> update charter test suite section

charter/index.html
#55 - sorry, I got the URL wrong with a cut and paste error. It was meant to link to this WGs LICENSE file. [https://github.com/w3c/webvr/blob/gh-pages/LICENSE.md](https://github.com/w3c/webvr/blob/gh-pages/LICENSE.md)
=> charter test code - got URL wrong

index.bs, index.html
Also added bikeshed error output to the makefile for my own sanity, and expanded documentation on existing events.
The new events are intended to communicate to the page author that something has happened that suggests that your page may want to enter (or pause/exit) VR presentation mode. First pass includes triggering proximity sensors (mount/unmount) and page navigation. I don't expect that this will be the only thing necessary to make VR links completely workable, we probably need a meta tag to suggest that the page is capable of VR presentation it so that UAs don't flash up non-VR content, but it seems like a piece that will be necessary regardless. These will be especially necessary if the UAs start requiring a user gesture to trigger VR mode, which I see as increasingly likely. …
=> Added VRDisplayEvent type and activated/deactivated events

index.bs
Trying to capture https://github.com/w3c/webvr/issues/71 opened by @kearwood
=> VRLayer.leftBounds and VRLayer.rightBounds is not null

index.bs
Rather than assigning null values, we should use the default, empty
array.
=> Make VRLayer.leftBound and VRLayer.rightBounds non-nullable (Fix #95)

index.bs, index.html
I encountered an error when running `make` due to this missing comma (and a stray trailing comma).
=> Fixes missing comma in enum for VRDisplayEventReason

index.bs
@cvan @toji 
Adding W3C mailing list and IRC to the participation section in Bikeshed doc.
Closes #129
=> Adding W3C mailing list and IRC

index.bs
This will match the behaviour of display and it makes sense for it to be non-nullable since it is already non-nullable in its EventInit dictionary.
=> Change VRDisplayEvent#reason to be non-nullable

index.bs
As discussed at Kirkland F2F. This can be added back in later after
further discussion to more precisely define what the timestamp is
relative to.
=> Strip timestamp out of VRFrameData

spec/latest/index.bs, spec/wip/index.bs
Thanks much @toji and @kearwood for adding me as a Spec Editor.  It's been such a great experience working with all of you on this standard.  There are also a couple more folks who have also been instrumental to Microsoft's contributions to the WebVR standard and it would be great to get them added as well.
=> Update Microsoft contributers

explainer.md
As of the Windows 10 Creators Update, Microsoft Edge now supports WebVR and developers can even get started without a headset using the [Windows Mixed Reality Simulator](https://developer.microsoft.com/en-us/windows/mixed-reality/using_the_windows_mixed_reality_simulator). Note that while WebVR is enabled by default in Microsoft Edge, using the Windows Mixed Reality Portal or Mixed Reality dev kits currently requires Developer Mode to be turned on in Windows settings.
=> Adding a reference to the Windows Mixed Reality headsets

explainer.md
This struck me as a bit odd when I saw it, so I asked around and it
seems like only one other web spec has a nullable enum (WebPayments)
and it’s not clear if it’s intentional or necessary that that was the
case. As such I think we should stick with the majority and make this
non-nullable.
That of course leaves a question of “What do we return when there is no
intrinsically associated eye?” My vote would be: Just return “left” and
be done with it. This attribute will probably only ever be used when
rendering content with pre-rendered stereo, and such content will
always need to pick an eye to present regardless of display mechanism.
(Realtime content generally won’t care about which eye is being
rendered, and will just use the prescribed view matrices.) By making
the API choose a …
=> Make VRView.eye non-nullable

explainer.md
While reviewing the current state of the API a few days ago I had a request to try and make the naming of the `compatibleVrDevice` context attribute and `ensureContextCompatibility` function more similar to enforce the fact that they both set the same internal state. I don't personally see it as being problematic, but I understand the request.
This is my proposed change, though in practice `vrDevice.setCompatibleVrDevice(canvas)` sounds a bit repetitive and slightly backwards. Very happy to hear other suggestions!
=> Proposed Name change: ensureContextCompatibility -> setCompatibleVrDevice

explainer.md
This brings it inline with all of our other asynchronous calls which
use the “request” verbiage. “Request” also implies that it can fail
better than “create” does.
I suspect this is an uncontroversial change, but I'll leave it as a pull request until I can at least bring it up on the call today.
=> Changed createFrameOfReference -> requestFrameOfReference

explainer.md
Suggestion to make this change came up during an API ergonomics review I did today. This lets us focus on the simple behavior of resolve/reject being the signal for support and allows us to extend the promise to return more information in the future if needed.
=> Change supportsSession promise to return void

explainer.md
Requested by @NellWaliczek. This is for the sake of clarifying things
for TAG review if we don’t get a better solution in place before they
look at the explainer, since we know this ISN’T the right way to handle
this. Ideally we’ll put it back in with #256 or a similar PR.
=> Remove the `navigation` event from the explainer

spec/1.1/index.bs
The descriptions for the vrdisplaypointerresticted and vrdisplaypointerunrestricted events were added to the webvr 1.1 spec in February, but the actual events themselves were missing from the idl.  This commit corrects that mistake.
=> Fixes pointer events missing from idl in 1.1 spec

explainer.md
Fixes #270.
Renamed `VRSessionCreateParametersInit` -> `VRSessionCreationOptions`
Moved attributes out of `VRSessionCreateParameters` and directly onto
`VRSession`
Putting this up as a pull request to allow some time to comment if anybody wants to.
=> Address a couple of comments about the session createParameters

.pr-preview.json
Enable pr-preview for the latest WebVR spec that automatically
links both preview and HTML diff from within the pull requests.
https://github.com/tobie/pr-preview/#pr-preview
=> Enable pr-preview

spec/latest/index.bs, spec/latest/index.html
Per general WebIDL direction https://github.com/heycam/webidl/issues/365
***
[Preview](https://s3.amazonaws.com/pr-preview/dontcallmedom/webvr/webidl-exposed.html) | [Diff](https://s3.amazonaws.com/pr-preview/w3c/webvr/f297d4f...dontcallmedom:d57be52.html)
=> Annotate interface with [Exposed] extended attribute

explainer.md
Following proposal in #282. This would definitely simplify a lot of the code in some of the samples I've been working on and I believe would make it easier for developers to create experiences that work on the widest possible range of devices.
Comments welcome!
=> Added section about `stage` emulation

spec/1.1/index.bs, spec/1.1/index.html, spec/latest/index.html
Ran `make` to rebuild the docs, which seems to pull in some other updates as well. (earlier commits did not `make` during commit time?)
=> Remove 'Deprecated API' label from WebVR 1.1 spec text. Fixes #288

explainer.md
Got an initial pull request up, but this is going to take some discussion.
The basic idea is to drop `getDevices` in favor of a `requestDevice` call that can take an optional set of filters. Credit where credit is due, this is basically what @cvan suggested we do [way back in January](https://github.com/w3c/webvr/issues/179#issuecomment-275284599). I felt that we should try and keep the API simpler. Jokes on me, I guess. ;)
Some of the important points:
This follows very closely the pattern already happily established by [WebUSB](https://wicg.github.io/webusb/#enumeration) and [WebBluetooth](https://webbluetoothcg.github.io/web-bluetooth/#device-discovery), right down the the exact function name. That immediately puts my mind at ease a bit, in that it means we feel more at home next to …
=> Refactor getDevices into requestDevice

spec/latest/index.bs
This:
- Makes the promise resolution value of requestDevice() method a
nullable type.
- Fixes the example snippet of requestDevice() method.
- Brings a note about requestDevice() behavior when multiple devices
are available from explainer.md and made part of it a normative bit.
***
[Preview](https://s3.amazonaws.com/pr-preview/jungkees/webvr/change-requestdevice.html) | [Diff](https://s3.amazonaws.com/pr-preview/w3c/webvr/27e1e6c...jungkees:16cb168.html)
=> Clean up around requestDevice()

explainer.md
I just noticed that the WebGL multiview extension spec moved to a slightly different location and the link in the WebXR explainer needs to be updated
=> Corrects Multiview Extension specification URL

explainer.md, spec/latest/index.bs, spec/latest/index.html
Simple change, but one that I want other vendors to LGTM before merging: Had a recent conversation where how we handle the case of not finding a device came up, and it made me question how other similar APIs do it. Previously I had advocated for resolving the promise with `null` in that scenario, but I realized there's prior art here. Turns out that WebUSB and WebBluetooth reject their `requestDevice` calls with a `NotFoundError` when there's no device that matches the given criteria. Therefore, for the sake of consistency on the platform, I feel pretty strongly that WebXR should do the same.
Any complaints?
=>  Policy change: reject `requestDevice` with `NotFoundError` if no devices found

spec/latest/index.bs, spec/latest/index.html
According to
https://www.khronos.org/registry/webgl/specs/latest/1.0/webgl.idl
WebGLRenderingContextBase is a mixin interface, add mixin in spec.
=> Add mixin syntax before WebGLRenderingContextBase interface

explainer.md
In the "Acquiring a Device" paragraph of "Lifetime of a VR web app" there is a mention of VR capability whereas it's not an example, thus XR is more generic and should be used here.
=> advertise VR functionality -> advertise XR functionality

explainer.md
And clarified the ones that are left to clarify that the API is
non-standard and suffers from implementation differences between
browsers. Addresses the concern brought up in #332. 
CC @blairmacintyre
=> Removed some references to device orientation events

explainer.md
Addresses #349.
Changes `framebufferScaleFactor` so that a value of 1.0 corresponds to the "default" framebuffer size and exposes a new static `XRWebGLLayer.getNativeFramebufferScaleFactor(xrSession)` function that reports the scale that should be used to get a 1:1 pixel ratio.
=> Change how framebufferScaleFactor is interpreted.

explainer.md, index.bs
The main purpose of this PR is to clarify what input sources are returned from a call to XRSession.getInputSources(). These changes make it easier to expose tracked hands on AR devices are exposed (eg, the HoloLens). 
I've renamed the `pointerOrigin` enum and members to `targetRayMode: { 'gazing', 'pointing', 'tapping' }` to better reflect the input intent, rather than physical representation. This was primarily to reduce confusion: since a tracked hand is actually uses the head gaze as a ray, so should be a `head` not a `hand` in the old nomenclature. 
The implication of this is that while it is up to the user-agent to determine if it is appropriate to merge multiple 0DOF input sources (clicker, gamepad etc.) into a single `gazing` input source, or expose them as multiple (eg, tracked …
=> Renamed pointerOrigin and enum values to reflect usage pattern, not device type.

explainer.md
If you're reusing the same canvas with the same context to render
the content inside the page you want to tell to unbind it from
the XRWebGLLayer. Not doing triggers warning in Chrome :
WebGL : INVALID_FRAMEBUFFER_OPERATION: cannot render to a WebVR
layer outside of a frame callback.
=> Unbind the framebuffer when the session ends.

explainer.md, index.bs
As discussed in #364 and confirmed on today's WebXR call.
'headModel' -> 'head-model'
'eyeLevel' -> 'eye-level'
This is a pretty straightforward change, and I intend to merge it in the next day or so if there's no additional feedback.
=> Updated enums to conform to the web platform's preferred casing.

explainer.md, index.bs
As discussed in #364 and confirmed on today's WebXR call.
'XRPresentationFrame' -> 'XRFrame'
This change is pretty straightforward, so I'll merge it in a day or two is there's no comments.
=> Rename XRPresentationFrame -> XRFrame

explainer.md, index.bs
I've gotten feedback from a couple of sources now that the naming for the `XRTargetRayMode` enums goes against the grain of web platform conventions a bit, specifically the "*ing" tense that they use. In the words of @bfgeek:
> The *ing names are a little out of place... It would probably make sense if the *ing were part of a state machine, e.g. "loading" an url. -> "loaded" an url. (see also "pending" etc.).
>
> closest thing we have on the web is pointerEvents.pointerType, which just uses "touch", "mouse", etc.
Of course, as @leweaver [remarked on the original pull request](https://github.com/immersive-web/webxr/pull/342#discussion_r190438762) "Naming is hard, yo." (@leweaver quotes may be paraphrased.)
So I'd like to discuss some alternatives, and an priming that conversation with some …
=> Change tense of XRTargetRayMode enums

explainer.md
Now that we've committed to using `DOMPointReadOnly` in `XRRay`, it looks a bit weird to have a separate "Point" type for stage bounds. Happily `DOMPointReadOnly` can work as a drop-in replacement with no changes to how the user would actually interact with the point array. The one thing that we'd want to specify is what the `y` value should be (I've explicitly made it 0 in this PR, since that sounds like a sensible default). `w` should be 1, identifying it as a point, not a direction, and staying consistent with our use in `XRRay`.
Any opposition to this change?
=> Replace XRStageBoundsPoint with DOMPointReadOnly

index.bs
Moves the unstable warning to use bikeshed mechanism for these alerts
Refers to immersivewebwg boilerplate in bikeshed, pending merging in bikeshet repo at https://github.com/tabatkins/bikeshed/pull/1360
=> Align spec metadata with Immersive Web WG ownership

explainer.md, input-explainer.md
This PR switches the inline/immersive mode selection from a boolean to a full enum and in the process introduces "Immersive AR" mode, which covers both phone and headset AR.
I fully expect that the naming I've chosen here will be a source of some controversy, but after a lot of thought I really do feel like something along these lines, that explicitly uses the terms "VR/AR" (or at least "virtual/augmented"), is the best for users. It's certainly true that it's a gross simplification from our standpoint as API creators and platform owners, but the truth is that nobody is going to start looking at our documentation saying "I want to build a app with an optically transparent headset that has access to environmental data!" No, they're gonna say "I want to build an AR app. Where do I start?" …
=> Introduce XRSessionMode enum, describe immersive AR mode.

index.bs
Update the existing spec text to take into account the changes made in #405, removing XRDevice.
=> Remove XRDevice from the spec text

explainer.md, input-explainer.md, spatial-tracking-explainer.md
Addresses the core issue of #412, though there's room for a follow up if we decide that having a default frame of reference is a good idea.
This PR makes the relatively simple change of moving the `views` array off of the `XRFrame` and under the queried pose, so that projection matricies that take into account the frame of reference if necessary. In my opinion this also simplifies the common case code a little bit and leaves less questions about why the various matrices are spread across the various interfaces instead of all in once place.
I've also taken the opportunity to rename the pose from `XRDevicePose` to `XRViewerPose`, taking a page from [@thetuvix's suggestion](https://github.com/immersive-web/webxr/issues/412#issuecomment-429583278). I'm happy to take additional naming …
=> Move Views array to Pose

index.bs
Nothing surprising here, just trying to reduce the delta between the spec and the explainer. Did some handwaving over a couple of algortihms to keep PR focused on just the updated parts.
=> Updating spec to account for recent XRView and XRFrame changes

explainer.md, input-explainer.md, spatial-tracking-explainer.md
Fixes #418. This is a pretty simple search-and-replace PR that just switches the explainers over to the new verbiage discussed in #418.
=> Rename CoordinateSystem/FrameOfReference => Space/ReferenceSpace

session-creation-explainer.md
The initial version contains background, a proposal, open questions & issues, and a discussion of alternatives.
There is also an additional proposal to add a Start() method to XRSession.
=> Add an explainer for session creation and configuration

explainer.md, input-explainer.md, spatial-tracking-explainer.md
Part of a solution to address #431. We've also heard from several developers that they end up decomposing the view matrices we supply so they can apply a translation and rotation to their engine's camera primitive, which feels annoying and error prone. This PR proposes that we start representing most transforms in the API as an actual transform interface, which includes a translation vector and orientation quaternion. (Both as `DOMPointReadOnly`) It also provides a Float32Array matrix attribute (which can be lazily evaluated for performance reasons) as a convenience.
Using a transform interface like this will allow transform inputs into the API (such as for teleportation in the follow-up PR) to enforce constraints that a simple matrix would not, such as ensuring that there is no shearing …
=> Introduce XRRigidTransform

spatial-tracking-explainer.md
Follow up to #440, second part of a solution to #431. This PR adds the ability for developers to specify a transform to any `XRReferenceSpace` that will be applied to any sensor-controlled poses, effectively giving developers a simple method of "teleporting" the user around a scene. (That's a bit over-specific, since this also allows for things like touch/mouse rotation of magic window content and continuous stick motion if you have the stomach for it.)
Technically this is something that any dev can do themselves, but it means ensuring that you're consistently applying the transform to all your inputs, manually reversing it out for things like hit testing, and inverting, applying, and re-inverting in order to apply to view matrices. Thus handling it in the API is a significant convenience …
=> Add application-defined Reference space transforms ("Teleportation")

index.bs
Relatively simple addition of a single attribute. In the process found that we were previously describing a `XRReferenceSpace` attribute (`session`) that should have just been an internal variable. Re-arranged that to make more sense.
=> Added originOffset to XRReferenceSpace

index.bs
baseLayer is null after construction, so the attribute must be nullable
=> baseLayer is nullable

explainer.md
This change introduces an `XRRenderState` object that encapsulates any values that get picked up on frame boundaries, which hopefully makes it easier for developers to reason about how and when those values are updated. Updates happen with a `updateRenderState()` function that takes in a dictionary and returns a promise that resolves once the updated values have actually been applied.
One extra bit of feedback I'd like on this: I feel like "RenderState" is the right term for these values, but @NellWaliczek has expressed that "RenderOptions" feels like a better name, saying that "State" feels like something you'd have to re-set every frame. I could live with either name, but given the difference of opinion between the editors I'd love to hear from the rest of the WG if one or the other …
=> Encapsulate session/frame render state into it's own interface

index.bs
The nullable marker is on the type, not the name of the dictionary member
=> Fix bug in WebIDL definition of XRSessionCreationOptions

explainer.md, spatial-tracking-explainer.md
This adds a new reference space type that takes the place of passing `null` as the mechanism to return identity poses. Move to handle it with a new space like this was due the desire to allow the `originOffset` to still be used even in situations with no tracking.
Nell and I had a question about whether or not the included code sample is something that belongs in the spec and/or explainer, since it's a pretty specific case and the purpose of this doc is not to teach anyone quaternion math. Still, it seems like a good demonstration of why this new type matters. Thoughts?
=>  Describe the identity reference space

explainer.md, input-explainer.md, spatial-tracking-explainer.md
This PR is intended to pave the way for making it easier to introduce new types of pose tracking functionality in the future by making how we query poses for almost everything more generalized. (The viewer pose is still special because it's the only thing that needs the `views` array, but even there this change makes it less of an outlier.) Ideally this change will make it much easier to reason about adding things like anchors in the future, and also serves to set the stage for #384 as well as fixing the frame-bound concern brought up in that issue.
=> Handle pose queries in a more generalized fashion

index.bs
We currently have `dictionary XRStationaryReferenceSpaceOptions: XRReferenceSpaceOptions`, and `requestReferenceSpace(XRReferenceSpaceOptions options)`.
WebIDL doesn't allow accepting a subtype dictionary as one of its parent types in a method argument, it will be upcasted first. This commit moves the `subtype` field to `XRReferenceSpaceOptions` and removes `XRStationaryReferenceSpaceOptions`, instead having some dynamic checks during `requestReferenceSpace()` to ensure the options are well-formed.
r? @toji cc @kearwood
=> Merge XRStationaryReferenceSpaceOptions into XRReferenceSpaceOptions

index.bs
Status metadata does not need "w3c/"
=> [Editional] Fixed metadata/status from w3c/ED to ED

explainer.md, input-explainer.md, spatial-tracking-explainer.md
This PR addresses a few related things I noticed now that the getPose() changes have landed
1. We were missing a section that focused on the descriptions of XRSpace and XRPose themselves. I added this to spatial-tracking-explainer.md and moved the XRRigidTransform and XRRay types to be together in that document's idl section
2. Having an XRSpace representing the viewer would be really handy for a few reasons. First, it would allow pose data to be queried relative to the viewer, such as "where are the hands relative to the headset?", without having to do extra matrix math. Second, it's easier to describe the consistent targetRaySpace for 'gaze' based input sources. Third, it becomes one of the XRSpaces from which hit testing can be done (See PR #493).
3. With both of the above changes in …
=> Add XRSession.viewerSpace and tidy XRSpace explanations

index.bs
Based on some observations made while attempting to implement `updateRenderState` in Chrome.
=> Describe exceptions that updateRenderState may throw.

index.bs
Previously the entire spec was contained in one big "unstable" section. This update changes that to only apply to sections of the spec that the editors (conservatively) feel may still see breaking changes. 
Sections not marked "unstable" are **not** considered "done". They are expected to still see updates to prose, algorithm improvements, and new additive functionality, but are not likely to have backwards-compatibility-breaking changes made to them going forward.
=> Narrow application of the 'unstable' markup in the spec

explainer.md
This was discussed at the Jan 2019 F2F as part of a broader topic of refactoring output contexts. Making output contexts mutable as described in the PR was seen as non-controversial while other aspects of the discussion did not reach an agreement.
Change moves setting the `outputContext` from a session-creation time event that was then immutable to part of the `XRRenderState`, which allows it to be changed at any point. `outputContext`'s can still only be associated with a single session at a time, so it will be removed from any previous session when reassigned.
=> Make outputContext part of the XRRenderState

index.bs
Pretty self-explanatory. We shouldn't execute callbacks if there's no render target, especially since that facilitates tracking the user movements without an associated visual changes.
=> Specify that frame callbacks are not called without a base layer

index.bs
This change defines a spec internal concept, XR device, distinguished from the
XR object's XR device internal slot. The XR device concept is not exposed to the
script surface but just used by spec internal algorithms. The XR device concept
represents an XR device and the XR object's XR device internal slot can hold an
XR device.
This change moves the definition of the list of supported modes from XR object's
XR device internal slot to XR device concept. This makes us be able to define XR
device's states under the concept rather than the platform object's internal
slot and write algorithm steps that reference those states more easly.
This change specifies navigator.xr attribute's getter and the creation of XR
object associated with a Navigator object.
This change introduces the Infra spec …
=> Introduce spec internal concept and start to use Infra spec definitions

explainer.md, index.bs
=> Clarified when immersive sessions are rejected

index.bs
Fixes #490 and #472.
Fixes the issues pointed out in the XRRay constructor as well as providing an explicit definition of the term "normalize" (which feels a little out of place in the spec, but I'm not really sure how to say "Just do the normal math thing here." is W3C-ese)
=> Clarify XRRay constructor and define normalization

index.bs, input-explainer.md
Fixed #515.
Thanks to @HyroVitalyProtago for the suggestion! Empty string was definitely a weird enum, and so I do feel like it's appropriate to change it to a more representative string. I had suggested `neutral` in the issue, but upon thinking it through further I feel like @HyroVitalyProtago's original suggestion of `none` is more appropriate. This is because the input in question may not actually be associated with any hand at all, such as is the case with gaze input, whereas `neutral` implies to me that the input is actually associated with a hand but doesn't know or care which. i.e: A Vive wand that hasn't established it's spatial relationship yet strikes me as a "neutral" input device, while a cardboard device has no hand association whatsoever. In both cases `none` feels like an …
=> Changed XRHandedness enum to use 'none' instead of ''

index.bs, input-explainer.md
Previous explainer text indicated that this scenario should have returned `null`, but that seems inconsistent with the behavior of other similar restrictions, so I've updated it to throw an `InvalidStateError`. Thanks to Jacob DeWitt (for whom I don't yet know a GitHub handle) for helping highlight the inconsistency!
=> Specify that getViewerPose throws an error for non-rAF XRFrames

index.bs
Fixes #482
Adding the `"identity"` reference space type. Not including `originOffset` at this point to keep PRs focused and easy to review.
=> Spec text for the identity reference space

spatial-tracking-explainer.md
As requested in #549.
This change brings the explainer's IDL signature back inline with the
version that's in the spec until we determine once and for all if we
should allow this function to accept an array or not.Tellingly, despite
multiple code examples using requestReferenceSpace only one, the one
explicitly showing the fallback behavior, was actually using the
"correct" form of the call prior to this PR.
=> Explainer: requestReferenceSpace no longer takes an array

explainer.md, index.bs
Fixes #523.
This value instructs the UA to prevent the values left in the depth buffer after a frame is rendered for compositing. Slightly concerned about potential for confusion regarding the `depth` and `ignoreDepthValues` attributes being on the same dictionary, so clarifying bikeshedding is welcome there if you have suggestions.
Given the scope of the feature it felt appropriate to handle both the spec text and explainer text in the same PR. Please take a look!
=> Add ignoreDepthValues attribute to the XRWebGLLayer

explainer.md, index.bs, spatial-tracking-explainer.md
Fixes #447.
Ooh, hey! I'm gonna try GitHub's shiny new "Draft Pull Request" thingy here. ('Cuz this PR is clearly not quite there yet, but I feel it's worth discussing anyway.)
This was discussed on the IW call today, but I'll recap here: There's been some ongoing discussion about removing `XRView.viewMatrix` because it's computable from the values given in the `XRView.transform`. I've been a bit reluctant to do that simply because if someone *is* using the matrix then this makes it significantly more involved to get the same value back.
Separately, we had a discussion around the `originOffset` at the January 2019 Face to Face and one of the outcomes of that was that no matter how we chose to interpret the value given there we'd end up feeling "backwards" about 50% of the time.
This CL …
=> Remove viewMatrix and add XRTransform.inverse()

index.bs
Also documents the algorithm for removing the ouputContext from previously bound sessions when a new session has been associated.
=> Spec: Move outputContext to XRRenderState

index.bs
Given that it's a float, comparison with 1 may not be the best idea, but I feel like erroring here is marginally better than ignoring invalid `w` values.
=> Validate position DOMPointInit

index.bs
Fixes #461.
At the January F2F we agreed that the `projectionMatrix` attribute
should remain a matrix to allow for more complex projections that
include, for example, shearing. In order to dissuade applications from
attempting to decompose the matrix into a view frustum, which wouldn't
properly account for that, this PR adds text to the spec that explicitly
states that decomposition is a bad idea and gives reasoning as to why.
=> Specify that projection matrices may include shear

explainer.md, index.bs
This addresses a concern brought up by @kearwood during the discussion
of #523. He pointed out that it would be useful for some apps to know
if the compositor actually was using the depth values in the case where
`ignoreDepthValues` was not set to `true` at layer creation time,
because that would allow some applications to skip an unnecessary
explicit depth write step that they otherwise would be happy to do if
they knew it would contribute to the final frame.
Following the pattern set by other WebGL-style attributes like
`antialias`, this PR indicates that the layer attribute should
communicate whether or not depth values are actually being ignored by
the compositor, rather than simply echo the boolean passed in at layer
creation time.
=> Indicate when compositing is using depth values

explainer.md, index.bs, spatial-tracking-explainer.md
Suggesting this change based on a conversation with @bfgeek about API ergonomics. His assertion was that if the XRRigidTransform object was (and always would be) immutable (which it is) then it would make sense to have the inverse be exposed as an attribute (lazily evaluated, of course) rather than a method. Using a method for a case like this is appropriate in scenarios where the desired behavior is to return something based on the current snapshot of a mutable object's state. But since the XRRigidTransform is immutable (and therefore will only ever have one inverse) we could opt for the arguably simpler syntax.
Thoughts?
=> Change XRRigidTransform inverse from a method to an attribute

index.bs
Fixes #556. Adds a catch-all statement that promises shouldn't outlive
the session they were returned from and indicates what error they should
reject with when the session shuts down.
Pinging @alcooper91 to take a look.
=> Reject outstanding promises on session shut down

index.bs, spatial-tracking-explainer.md
Fixes #576. Specifies that the object returned by `XRRigidTransform`'s
`inverse` attribute must always be the same JS object and, furthermore,
the `inverse` of a transform returned by `inverse` must be the
originating transform.
=> `inverse` attribute always returns the same object

explainer.md, index.bs
Fixes #272.
Pretty simple feature, based on the feedback from the F2F. It's apparent to me that we're not going to magically come up with a default value that has a good reason behind it, so I plugged 90deg in there just because it's a clean number that's easy to guess and gives reasonable results. Also left it as a single direction that can be specified (vertical) because you can pretty trivially do the math to convert from one to the other and vertical seems to be the value that most developers/game players are used to setting. (This because monitors are traditionally wider than tall and it's easier to get predictable results out of a single vertical FoV when jumping between 4:3 and 16:9 aspect ratios).
=>  Add inlineVerticalFieldOfView to XRRenderState

explainer.md, index.bs, spatial-tracking-explainer.md
As described in #542, this switches `requestSession` to a "primary type
plus options bag" pattern. However, since the dictionary only had a single
key after outputContext was moved this change ends up removing the
`XRSessionCreationOptions` dictionary entirely in favor of just passing in
the type enum directly.
In the future if additional options *are* needed for `requestSession`,
the expected pattern would be:
```
navigator.xr.requestSession('immersive-vr', { option: value });
```
=> Remove XRSessionCreationOptions

explainer.md, index.bs, spatial-tracking-explainer.md
Fixes #513 
Addresses some discussion in #514, but doesn't change the enums.
This PR removes the `mode` attrib from `XRSession`, the `depth`, `stencil`, and `alpha` attribs from `XRWebGLLayer`,  and the `subtype` attrib from `XRStationaryReferenceSpace`. Since that left `XRStationaryReferenceSpace` with nothing else in it, I also took the opportunity to consolidate it and `XRUnboundedReferenceSpace` into `XRReferenceSpace`.
=> Remove attribs that only reflect requested values

index.bs
=> [Editiorial] Status metadata does not need "w3c/"

index.bs
Reverts immersive-web/webxr#594
=> Revert "[Editiorial] Status metadata does not need "w3c/""

explainer.md, index.bs
Fixes #592. Brings name inline with requestSession, which now takes the
same arguments.
This is a simple enough change that I figured I'd just have a PR ready to go if we agree with #592.
=> Rename supportsSessionMode to supportsSession

index.bs
Fixes #588
There are only two non-primitive `readonly attribute`s that this does not affect:
- `XRSession.renderState`: This can be updated with `updateRenderState()`
- `XRBoundedReferenceSpace.boundsGeometry`: I'm unsure if this array can be updated if settings change
r? @toji
=> Add [SameObject] to all applicable readonly attributes

index.bs
This change fixes strings to the XRSessionMode values, uses the same format for
DOMExceptions, and makes the Initialize the session algorithm more explicit by
defining parameters to it. This does not have any behavioral change.
=> Edit requestSession() and Initialize the session

index.bs
r? @toji
I went to update the spec text to clarify that XRRenderState is a live object, but it's already pretty clear on that it seems. Let me know if I should update something.
Fixes #600
=> Mark XRRenderState as [SameObject]

index.bs
We removed the `viewMatrix` attribute quite a while ago.
=> [minor] Views don't provide view matrices anymore

index.bs
Formalizes the definitions of origins, transforms, and some of the math
involved. This will hopfully give us a better foundation on top of which
we can better talk about spacial concepts.
**Huge** thank you to @klausw and @Manishearth for helping to iterate
through this fairly tricky language and land on something that should
be much more formal while still being (hopefully) easily readable.
=> Overhaul XRSpace, get(Viewer)Pose definitions

index.bs
These are bools and enums which aren't objects, `[SameObject]` will not work on them.
r? @toji
=> Remove non-object [SameObject]s

index.bs
Fixes #580. Changes originOffset to be immutable and establish that the
way that the originOffset changes is by creating a new reference
space with the `getOffsetReferenceSpace()` method of the base space.
This should hopefully solve several timing issues related to changing the
originOffset mid-frame.
=> Make origin offset immutable

index.bs
Moved from https://github.com/immersive-web/webxr/pull/610 which got accidentally closed due to a branch being deleted
fixes #565
=> Explicitly specify how the views array is populated

index.bs
It was pointed out to me that even though we consider "unknown" to be the default fallback value for gamepad ids prior to more thorough speccing, that string doesn't actually appear anywhere in the spec yet! Whoops!
=> Identify cases where the Gamepad id should be unknown

index.bs
Brought up by @blairmacintyre in https://github.com/immersive-web/webxr/pull/609#discussion_r279159519
To repeat the concerns there: This makes less sense when in a vehicle, and even less sense in space. It's adequate to define the Y axis as being a deliberately vague notion of "up", since that's more tied to user perception rather than physical concepts. That should be enough to get people to match implementations
(The orientation of the Y axis of natural origins isn't observable if it's consistent across origins anyway, but it's good to avoid overspeccing where unnecessary)
r? @toji
=> Remove gravity mention

explainer.md, index.bs
Fixes #617
This method has been identified as a target for deferring until a future
version of the API, due to it's difficulty to use effectively and
overlap with framebuffer scaling for quality control.
=> Remove XRWebGLLayer.requestViewportScaling()

index.bs, input-explainer.md
/Fixes #608
Changes the `getInputSources()` method on `XRSesssion` to a readonly
attribute `inputSources`. This better reflects the expected behavior
of the returned array being a live object that is updated in-place as
input sources are added and removed.
=> Change inputSources getter from method to attrib.

index.bs
Fixes #465.
Defines what should happen as input sources for a session are added,
removed, and changed. Also clarifies the definitions for some of the
related concepts.
=> Describe how the input source list is maintained

index.bs
Fixes #540
Defines the order that events fire in during the handling of transient events.
=> Define event order of input sources

index.bs, spatial-tracking-explainer.md
Renames several reference space types for clarity, as recommended in
issue #633. Intent is to better communicate which reference spaces are
floor-aligned and avoid potential developer confusion that may arise
from use of the term "stationary".
Renamed reference spaces:
- `eye-level` -> `local`
- `floor-level` -> `local-floor`
- `bounded` -> `bounded-floor`
=> Rename reference space types

index.bs
"and abort these steps" is unnecessary as these steps are aborted two steps later. This would also prevent "pending immersive session" from being cleared.
=> Remove redundant "abort these steps" in requestSession() algorithm

index.bs
This makes the algorithm a little easier to read.
=> requestSession(): Group steps to run when promise is rejected

index.bs
/fixes #593
The behavior in question is already explicit via the `[SameObject]` extended attribute, but a non-normative note felt appropriate to ensure that the implications of that were clear for developers.
=> Added non-normative note about gamepad liveness.

index.bs
The multiplication order in the spec needs to match the matrix
semantics we've agreed on, and the usage appeared to be backwards.
Specific justifications following.
getViewerPose: if |offset| is the view offset of an eye view, the expected
semantics would be that it's a pose-like transform where the transform's
position is the eye view's coordinates in XRViewerPose space. The
corresponding matrix is viewerFromEye. XRViewerPose contains the viewer
pose in the base reference space, so its transform's position is the viewer
position in base space coordinates, and the transform is baseFromViewer.
Chaining these transforms works as follows:
```js
offset.matrix = viewerFromEye;
viewerPose.transform.matrix = baseFromViewer;
view.transform.matrix = baseFromEye
= baseFromViewer * viewerFromEye
= …
```
=> Fix multiplication order for transforms

index.bs
We've been circling around whether transforms are "transforms from" or "transforms to" a bunch, see https://github.com/immersive-web/webxr/issues/582#issuecomment-492879145 , https://github.com/immersive-web/webxr/pull/649#issuecomment-492772969 for the latest examples.
These are some clarifications that may help.
I have a potential fix for #582 ready as well, but I want to land that separately since that actually adds new semantics as opposed to clarifying existing semantics.
cc @klausw @thetuvix
=> Some matrix clarifications

index.bs
Fixes #647
Contains no behavior changes, only formatting. In some cases we had "If foo do ... and abort these steps. Else do ...", I just simplified these cases by removing the else.
[Rendered](https://api.csswg.org/bikeshed/?force=1&url=https://raw.githubusercontent.com/Manishearth/webxr/conditionals/index.bs)
cc @ddorwin
r? @toji
=> Properly format conditionals

index.bs
Addresses concerns raised after landing #654
The use of `referenceSpace` here may inadvertently suggest that it only
takes an `XRReferenceSpace` object, when in reality it can take any
`XRSpace`. Using `baseSpace` as a replacement at the suggestion of
@klausw and @thetuvix.
Plus it's fun to say: `getPose` finds the place of your space in the
baseSpace's space! 😉
=> Rename getPose arg referenceSpace->baseSpace

index.bs
/fixes #622
Specifies that touchpads that aren't actively being touched MUST report axes of 0. If/when this policy gets adopted by the Gamepad API we can remove this additional restriction.
=> Clarify what value a touchpad should report when not being touched.

index.bs
I'm not 100% sure if I like the existence of this attribute, but I took a stab at making it conceptually unique. While there are many 3D rotations between two vectors, there is only one 2D rotation (and also, it is the easiest to compute -- most algorithms for "rotation between two vectors" will give you this). Such a rotation will basically keep the perpendicular to `direction` and `-z` unchanged.
I've added text specifying that the matrix must be of this type, as well as a partial algorithm for computation (I don't elaborate on how the axis-angle rotation matrix is to be obtained)
fixes #582
cc @thetuvix @bialpio
=> Make XRRay.matrix unique, add steps for obtaining it

index.bs
Applications should not be able to obtain any additional information without user activation.
=> requestSession: Check for user activation first

index.bs
Many areas of the spec have stablized since that markup was added, so
this commit does a pass over the entire spec to ensure that the
"unstable" label is applied approriately. Also took the opportunity to
fix a couple of minor typos.
=> Remove 'unstable' label from multiple sections

explainer.md, index.bs
/fixes #268
Also changed `baseLayer` to only accept an `XRWebGLLayer`. This can be
extended in the future in a few ways:
- Re-introduce XRLayer and change `baseLayer` to take one.
- Update `baseLayer` to accept a union of layer types.
- Leave `baseLayer` as WebGL-only and enforce that new layer types must
use whatever layer array mechanism is introduced.
=> Remove XRLayer base type.

index.bs
/fixes #583
The gamepad API specifies that the index is a long. It's only Chrome's implementation that uses an unsigned value.
=> Change required gamepad index to -1

index.bs
fixes https://github.com/immersive-web/webxr/issues/678
cc @ddorwin
r? @toji
=> Replace 'list of pending render states' with 'pending render state'

index.bs
fixes https://github.com/immersive-web/webxr/issues/469
I don't really address the "immersive session left at a part of the room to be returned to" concern, I'm not sure how that can be handled or if that even should be handled by immersive-ar the same way.
r? @toji
=> Clarify that small overlay UIs are allowed in exclusive access

index.bs
Fixes https://github.com/immersive-web/webxr/issues/712
- Consistently say "Queue a task to fire"
- Don't say "fire a simple event", just say "fire an event"
- Link to DOM spec for firing an event
cc @ddorwin
=> Cleanups on event text

index.bs
After #685, there is only one failure path at this point, and these steps can be simplified.
This also addresses incorrectly rejecting with `null`.
=> Simplify handling of unsupported modes in requestSession()

index.bs
Fixes for current algorithm to obtain XRRay.matrix:
- Dot product does not result in an angle between 2 vectors but is used as such.
- Magnitude of cross product of 2 vectors can be 0 but rotation can still be necessary.
Additionally, it seems that there used to be some trailing whitespace that got removed by my editor.
=> Fix algorithm to compute XRRay.matrix

index.bs
/fixes #352
Due to the variations between how different platforms handle window
animation frames when immersive content is running, making sure that
apps handle the transition between the window and session animation
loops gracefully is unfortunately unintuitive. This adds an example that
demonstrates one way to do it correctly, while also explaining the
problem.
@NellWaliczek: I'm a bit torn on where to put this. It feels out-of-place
in the spec. I can easily move the text over to the explainer if you feel
it would be more appropriate, but I worry that it would be overlooked
there. Thoughts?
=> Document how to transition between window and session animation loops.

index.bs
Fixes #658, fixes #635
take 2 at https://github.com/immersive-web/webxr/pull/704
This separates the concept of immersive XR devices (which participate in selection, and can be null) from the inline XR device (a guaranteed XR device representing the device containing the screen the browser window renders to). It explicitly adds the concept of the _session_ having an XR device so that you may have different sessions with different devices. There's a bunch of disambiguation done here to clean that up.
cc @ddorwin
=> Add an explicit inline XR device

images/xr-standard-mapping.svg, index.bs, input-explainer.md
Addresses concerns brought up in #695 
This will make cross-platform implementations more compatible by
removing some level of platform option from the mapping process. It will
also make it more practical to expose the discussed "profiles" concept
by making it easier to have inter-compatible sets of profiles.
Also took the opportunity to normalized on the verbiage "thumbstick"
instead of joystick, since that appears to be the official verbiage used
by all the device vendors.
=> Made the xr-standard gamepad mapping more rigid

index.bs
/fixes #724
Until we get some better guidelines in place regarding what kind of
mitigations are appropriate for using the `visible-blurred` state when
sensitive UI is being displayed, simply require that the content is
hidden instead. `visible-blurred` may still be used in less sensitive
cases where the XR content is not in the foreground but still visible.
=> Require that sensitive UI hides WebXR content

input-explainer.md
This supporting PR for #695 defines an initial set of generic `XRInputSource` profiles that are recommended to be used as a last-resort fallback when describing a device. It's very controller-centric right now, but I don't really object to adding additional profiles like "hand" if  everyone things that's useful to define right now.
=> Define initial set of generic profiles

privacy-security-explainer.md
Ok, hopefully in the home stretch now!
This PR is based on top of #739 and it is somewhat related, but is primarily attempting to incorporate the guidance that was laid out in #638 in a way that aligns with developer intent and the structure of the specification.  In other words, it is intended to be the foundation of the spec text changes we need to make next.  In that next PR, I'm expecting that the algorithms for each "signal" API call will be updated to depend on a combination of algorithms and internal variables which are described (roughly) in the bulleted lists in this PR.
Odds are I've missed or misrepresented some of the threats/mitigations covered in #638, so please do let me know what needs fixing up.
/fixes #393, #485
=> Filling in threat mitigations in privacy-security-explainer.md

explainer.md, index.bs, spatial-tracking-explainer.md
This is the corresponding spec text for the functionality described in
PR #739. There's some hand waving going on around user consent and such
because those will be better defined in a follow-up PR. The primary goal
of this PR is to establish the algorithims that drive how the feature
requests are processed.
=> Spec text for required and optional features

index.bs
Pulls a lot of text directly out of privacy-security-explainer.md to
define some of the various terms necessary to discuss user consent and
the data that it protects. This PR does not include several things from
the privacy explainer such as the restrictions on pose data and data
mitigation strategies. I expect to address them in a follow-up PR.
=> Spec: Define sensitive information and user intent

index.bs
/fixes #751
Details that consent dialogs may not be displayed while an immersive
session is active, and explains that this is a short-term restriction.
I chose to go with terminating the session in this case rather than
suppressing the consent dialog altogether, since it provides very clear
feedback about the error case and doesn't require us to make up new
behavior for the permissions in question.
=> Block mid-session consent requests

index.bs
/fixes #769 (sort of).
The previous logic to return `null` in situations where the passed view
was from a different session was not consistent with the error behavior
elsewhere. As a specific example, passing spaces from one session to an
XRFrame from a different session throws an `InvalidStateError`. As such,
throwing the same error here for the same type of validation makes the
spec more internally consistent.
=> getViewport with an invalid view throws an error

index.bs
Describes the mitigations and checks that must be used when returning
pose data from the API. Also includes discussion of data adjustments
and the privacy considerations for returning immersive sessions. Pulls
heavily from privacy-security-explainer.md.
=> Spec: Pose privacy considerations

index.bs
Describes the mitigations and checks that must be used when supporting
the various reference spaces. Pulls heavily from text originally in
privacy-security-explainer.md.
Posted as a draft because I'm not sure if I'm happy with the format yet.
=> Spec: Reference space privacy considerations

index.bs
/fixes #672 
**Do not merge until the [June milestone](https://github.com/immersive-web/webxr/milestone/9) is complete**
(I mostly just want the related issue to stop showing up in the [non-pending list](https://github.com/immersive-web/webxr/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+milestone%3A%22June+2019%22+-label%3A%22fixed+by+pending+PR%22))
=> Remove the Unstable banner from the top of the spec.

index.bs
This PR replaces "a" with "an" for the followings in index.bs
- a environment blending mode value
- a enum
- a active boolean
- a inline session's output context
- a end event
- a inputsourceschange event
=> Correction of article(a/an) in index.bs

index.bs
This might be useful for anyone searching for the term. The abbreviation was already present for the other reference to interpupillary distance.
=> Add IPD abbreviation to another location

index.bs
Fixes https://github.com/immersive-web/webxr/issues/783
r? @toji
=> Fire input source events when profiles changes

index.bs
Fixes https://github.com/immersive-web/webxr/issues/671
There's actually no direct algorithm for WebGL framebuffers that can handle these, typically you control these via `framebufferRenderbuffer` and `framebufferTexture2D` which our code forbids.
Instead, I looked at how the primary drawing buffer handles this in WebGL and updated the opaque framebuffer text to work with that, since its purpose is to match the drawing buffer anyway.
r? @toji
=> Explicitly mention how depth/alpha/stencil values get used

index.bs
Fixes https://github.com/immersive-web/webxr/issues/698
For enforcing `near < far` I don't think we should be throwing an error due to the two-step nature of applying render states. Instead, perhaps we should set near=far or something? (and encourage UAs to warn to the console). Alternatively, we can throw an error when the pending render state is created, but that can be a bit unpredictable.
cc @cabanier
r? @toji
=> Allow UA to constrain clip planes

explainer.md, index.bs
Based on today's call, we have agreed to move the environment blend mode into the ar module.  This PR removes it from the core WebXR spec.  An associated PR will be posted to add the mode into the AR module.  This PR will remain in draft mode until the other PR has been posted.
Based on today's call, we have agreed to move the environment blend mode from the WebXR Device API to the WebXR Augmented Reality Module. This PR removes it from the core webxr repository.  The associated PR to add it to the webxr-ar-module repo is https://github.com/immersive-web/webxr-ar-module/pull/2
=> Remove Environment blend mode from spec and explainer

index.bs
/fixes #791 
Updates the `requiredFeatures`/`optionalFeatures` dictionary keys to accept sequences of `any` values for forwards compatibility purposes. (Namely, enabling `optionalFeatures` to always ignore unknown values even if non-enum feature are introduced in the future.)
After the discussion in the above issue, I talked to @bfgeek about how to approach this particular concern. From that conversation it seemed that we either wanted to make this a array of [`object`](https://heycam.github.io/webidl/#idl-object) or an array of [`any`](https://heycam.github.io/webidl/#idl-any), depending on which seemed to fit our use case better. I tested both in Chrome, and both value types worked. I chose `any` for the PR here because in Javascript strings are not considered to be "objects" (ie: …
=> Change features to a sequence of 'any'

index.bs
The one remaining instance is a non-normative reference to "a desktop browser" where this is relevant to the example.
=> Replace "browser" with "user agent" where appropriate

explainer.md
As pointed out in https://github.com/w3ctag/design-reviews/issues/403. There is no default session mode anymore, it must always be specified explicitly.
=> Remove reference to inline being the default mode

index.bs
Fixes https://github.com/immersive-web/webxr/issues/808, all `Float32Array` attributes should consistently not be `[SameObject]` and should hadle detached buffers.
r? @toji
=> Handle detached buffers in projectionMatrix

index.bs
The former is incorrect for devices that are not head-mounted.
=> Replace "user's head" with "viewer"

index.bs
With https://github.com/immersive-web/webxr/issues/636 stereo inline sessions aren't possible anymore since you need a separate presentation context (or at least a separate framebuffer) to make that work. This PR removes some of the older text allowing stereo inline sessions.
In the future we may add diorama support (see https://github.com/immersive-web/webxr/issues/756, https://github.com/immersive-web/proposals/issues/31), but for now the spec shouldn't allow a thing that it renders impossible anyway.
=> Disallow stereo inline sessions for now

index.bs
For steps that are really related to inline sessions, check that directly for clarity.
This also avoids needing to consider things like #817 for these steps.
=> Check whether a session is inline rather than immersive when appropriate

index.bs
The algorithm for these already specify that it's a new object, this just annotates it in the WebIDL.
(I noticed this when thinking about #845)
r? @toji
=> Add [NewObject] to some methods

index.bs
Not intended for merge until discussed at TPAC /facetoface
Would fix #837 and #838 if the working group's decision is that `XRWebGLLayer`s are always treated as using premultiplied alpha regardless of the source context's flags. Preparing this for easy approval should that be the case.
=> Specified that XRWebGLLayer framebuffers always use premultiplied alpha

explainer.md, input-explainer.md, package.json, privacy-security-explainer.md, spatial-tracking-explainer.md
/fixes #847
As demonstrated by #818, uses [doctoc] to generate tables of contents for all of our explainers. Some additional work could be done to make the results a little more terse, but this feels like a good first step. To update when the documents change, run `npm run doctoc`.
Also pulled over one or two minor changes from #818 that I liked and were easy to do quickly, but I'd like to do a more thorough pass at that later.
=> Add a table of contents to the explainers

index.bs
This PR fixes minor typo, removing duplicated "include" from "include include".
=> Minor typo fix

index.bs
This PR fixes missing "and" in populate the pose section.
```
Else if limit is false "and" the tracking system provides....
```
=> Fix missing and in populate the pose

explainer.md, index.bs
Not intended for merge until discussed at TPAC /facetoface
Would fix #824 if this is the direction the working group agrees on.
Acts on feedback from the TAG that supportsSession should
resolve with a boolean rather than reject when a session mode is not
supported. In order to aid developers the method name was changed so
that previous uses of the old method will be clearly identified as
failing, rather than silently report that a session was supported that
shouldn't be because the app failed to check the resolved boolean value.
=> supportsSession->isSessionSupported, resolves w/ bool

index.bs
Not intended for merge until discussed at the TPAC /facetoface
Would fix #823 if the working group agreed to the suggested behavioral change from that issue. For a broader look at the editors proposed approach to Feature Policy handling within the Immersive Web APIs, please see https://docs.google.com/document/d/1RZTL69JsTxoJUyXNnu_2v0PPILqrDpYW3ZxDjMAqQ-M/edit?usp=sharing, which will also be discussed at the face to face.
=> Update behavior, name of Feature Policy

index.bs
/fixes #775
This pulls some language from the WebGL spec pretty directly to emphasize that we really just want the same behavior. Also has effectively the same non-normative note to indicate that lazy clearing is OK.
(Also fixed some inconsistent casing on a couple of unrelated non-normative notes because it was bugging me.)
=> Decribe the required clear behavior of an XRWebGLLayer

explainer.md
/fixes #861
Explains the rational behind why XRWebGLlayer uses an existing WebGL
context rather than creating it's own.
=> Note explaining why API shares canvas GL contexts

index.bs
/fixes #879
Made the wording of the reference space type descriptions more
consistent, since previously only `bounded-floor` and `unbounded` made
any mention of being conditional on session/device support (even though
that's made explicit in the algorithms.) This may have given the
impression that additional logic applied to these types beyond what the
algorithms dictate.
=> Clarify reference space type descriptions

index.bs
/fixes #881
Provides a bit more explanation as to what depthNear/Far mean and why
they're specified when other aspects of the projection matrix are not.
=> Better define how depthNear and depthFar are used.

explainer.md
/fixes #828
Expands the code samples given for how to use the `transform` from an `XRView`, showing both how to get a view matrix directly and how to apply the `position` and `orientation` attributes to a rendering library's camera object.
=> Expand XRView use code samples

index.bs
Half of the fix for https://github.com/immersive-web/webxr-ar-module/issues/32, will have a corresponding PR in the WebXR AR module to remove the WebIDL definition from that spec.
=> Move "immersive-ar" mode back into the core spec

index.bs
Somewhat nitpicky I suppose. If it had just been one, I might have ignored it, but once I saw the second and then more, I started getting twitchy. Ah, the live of a professional writer with a severe case of OAD (Obsessive Apostrophe Disorder). All places which previously used "it's" that should have been "its" are corrected by this change.
=> Corrections of "it's" to "its"

index.bs
/fixes #876
This adds an optional "primary squeeze" mirroring the "primary action". Once this lands we can backreference it [from the gamepads module](https://immersive-web.github.io/webxr-gamepads-module/#xr-standard-gamepad-mapping).
This also cleans up the primary action spec text to make the primary action a requirement.
cc @thetuvix
=> Define squeeze events

index.bs
The IsDetachedBuffer line isn't rendering as indented, which changes the meaning of the spec.
r? @toji
=> Fix indentation

index.bs
This paragraph appeared twice, both before and after the "on-squeeze-end" algorithm, likely as a result of a merge conflict. Delete the first copy of it, keeping the second one before the "on-input-cancelled" algorithm.
=> Deduplicate paragraph for primary action cancel

index.bs
Addresses half of #225. Indicates that there's no relationship between window.rAF and session.rAF, but also makes it clear that immersive sessions may prevent window.rAF from running in some circumstances.
This seemed to be the fairly clear conclusion that was reached regarding rAF behavior on #225. requestIdleCallback behavior seemed a little less agreed upon and thus a solution is likely to warrant more conversation, which is why I'll address it separately.
=> Describe interactions with window.rAF

webvr-migration.md
I've had several requests from developers for a resource about how to migrate WebVR code to WebXR. I've been sharing this around in Google Docs form, but decided it would be more effective as a markdown doc on this repo for easier linking.
This is a big doc, so don't feel compelled to try and validate every link or anything like that. Mostly looking for broad approval that such a doc belongs in this repo and that the content is laid out effectively. (Oh, and do yourself a favor and use the "rich diff" view on this one.)
=> Added a migration guide from WebVR

index.bs
This makes it easier to do things like in https://github.com/immersive-web/webxr-gamepads-module/pull/22 , where we want to be able to insert an action that occurs on the main thread whenever a frame is about to be processed.
=> Tighten up spec text around frame timings, add hook for frame updates

index.bs
Based on feedback from @bzbarsky, this pull request contains fixes for the following issues:
/fixes #910
Ensures that the logic that the getContext algorithm follows more closely
the logic and results of the makeXRCompatible algorithm.
/fixes #911
/fixes #908
Removes the requirement that a part of the makeXRCompatible algorithm
be performed in parallel, which both simplifies the logic and
solves some concurrency issues with setting the XR compatibile boolean.
/fixes #912
Specifies the task source for makeXRCompatible task.
We'll also want to do a larger review of the spec to determine the task
sources for any other tasks that we're queueing.
In addition to the usual editors cross review, I'd especially appreciate @bzbarsky's feedback and believe that @foolip may also want to take a look.
=> Multiple fixes to XR compatibility algorithms

index.bs
The text defining it already allows it to be null
=> Mark XRWebGLLayer.framebuffer as nullable

index.bs
This bullet point repeats itself with both "When not in a requestAnimationFrame() callback..." and "... outside of a requestAnimationFrame() callback" in it. Removed the second one from the sentence.
=> Remove duplicated phrase

index.bs
This was kind of missed in https://github.com/immersive-web/webxr/pull/737
Basically, if the user "switches into" viewing the page on an immersive XR device after the page has already loaded, inline sessions should be able to use and request tracking.
This does mean you can request an inline session while viewing the page in immersive mode, remove and disconnect the headset, and then have an inline session that was previously allowed to use tracking spaces but no longer can. This is a bit of a weird wrinkle but I think in the current situation it will just refuse to return poses, which is fine.
r? @toji
=> Potentially update the inline device when the device changes

index.bs
/fixes #937 
Adds some clarifying text to the `XRBoundedReferenceSpace` definition to indicate that the `boundsGeometry` array must be set to an empty array (`[]`) if the bounds are not known, and that `bounded-floor` reference spaces are allowed to be returned even if the floor level or bounds geometry hasn't yet been resolved as long as the device is known to support it.
CC @thetuvix
=> Clarify bounded reference space behavior

index.bs
/fixes #936 
If we're going to change the name of the `XR` interface to avoid conflicts we ought to do it soon. Of the alternate name suggestions put out thus far I liked @nbutko's `XRSystem` best by a large margin, not least of which because it aligns well with OpenXR's use of the term System for a similar concept.
To reiterate, while this does introduce some very minor backwards compatibility issues it's not expected to affect the vast majority of pages, may fix problems for a small number of them, and will generally be opaque to developers not working on, say, the polyfill.
=> Rename XR interface to XRSystem

index.bs
Declaring a `let` variable globally and then setting its value inside a `.then()` is bad practice and can lead less experienced programmers down a faulty (or even racey) path.
I’d recommend using modern JS with async/await. I only updated the first example here to start a discussion, I am happy to update the later example if the spec editors find this beneficial and/or valuable :D
=> Improve code style in example

index.bs
This is an editorial change to align the `<dfn>` markup for `XRSystem` members with the interface name change from "XR" to "XRSystem".
=> Change for="XR" -> for="XRSystem" in some <dfn>s

index.bs
[Rendered](https://api.csswg.org/bikeshed/?force=1&url=https://raw.githubusercontent.com/Manishearth/webxr/consent-tracking/index.bs)
This makes our feature request algorithm reuse machinery from the [Permissions API](https://w3c.github.io/permissions), making it possible to do things like query consent status.
We define a _single_ "xr" feature, however the query is done through a new `XRPermissionDescriptor` type which contains additional information about the requested features and the session.
In the current implementation, requested features are not persisted across sessions (which enables sessions with different modes, and sessions using different devices to have different granted features). However, there is nothing stopping the user agent from persisting granted features where it …
=> Use permissions API for XR feature requests

index.bs
Unsure if I should use a FrozenArray or an `any[]` here, I think it's fine to use a frozen array even though the attribute _can_ change because then the entire attribute will change (it's not `[SameObject]`)
/fixes #965 
r? @toji
=> Turn XRPermissionStatus into an interface

index.bs
This cribs very directly from the equivalent [WebGL spec text](https://www.khronos.org/registry/webgl/specs/latest/1.0/#2.2), with appropriate verbiage changes. Related to #969, but doesn't actually fix that one since the issue itself is more about what happens when the users doesn't dirty the framebuffer for a while.
=> Defining when an opaque framebuffer is considered dirty

index.bs
Recently the definition of [User Activation](https://html.spec.whatwg.org/multipage/interaction.html#tracking-user-activation) in the HTML standard has changed. Most notably, it was divided into concepts of ["sticky activation"](https://html.spec.whatwg.org/multipage/interaction.html#sticky-activation) and ["transient activation"](https://html.spec.whatwg.org/multipage/interaction.html#transient-activation), and specs that rely on activation behavior (like ours) need to update to indicate which them mean. The chromium team also put together a [brief guide for specs that need to migrate](https://docs.google.com/document/d/14wT89JZ0qeRehXGkcn3_meXxjvlHKgM9d7aJj80kQcQ/edit).
In our case I think it's pretty clear that transient activation is the right choice, since that's generally what we …
=> Updated the spec to match the latest user activation definitions

index.bs
/fixes #984
This makes some changes to how we pick inline devices that make the spec line up more closely with the group's intent for when inline sessions are allowed to expose tracking data, as well as add a bit of non-normative text to more clearly explain the purpose of the default inline session that can be accessed without first gaining user consent.
CC: @pes10k
=> Clarify when tracking/input data is exposed via inline devices

index.bs
We don't want to encourage !depth&&!stencil result if depth xor stencil.
=> Allow depth&&stencil result if depth||stencil requested.

index.bs
=> Allow cancelling rAF callbacks from within rAF

index.bs
Fixes #961
As mentioned in #961, this is not the only way to fix this issue; the other way to fix it involves changing the spec so that `inputSources` can start off non-null, however that involves ensuring the ecosystem respects that as well.
r? @toji
cc @cabanier
=> Defer initial inputsourcechange event till after the promise resolves

index.bs
Fixes #856
r? @toji
cc @asajeffrey
=> Mention that the opaque framebuffer holds a reference to a particular session

index.bs
Fixes #943
***
<a href="https://pr-preview.s3.amazonaws.com/Manishearth/webxr/pull/1015.html" title="Last updated on May 1, 2020, 6:05 PM UTC (e74bcff)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/immersive-web/webxr/1015/86839d2...Manishearth:e74bcff.html" title="Last updated on May 1, 2020, 6:05 PM UTC (e74bcff)">Diff</a>
=> Use current timestamp for rAF() callback arguments

index.bs
Added text for each object creation saying which realm they get created in.
***
<a href="https://pr-preview.s3.amazonaws.com/asajeffrey/webxr-spec/pull/1023.html" title="Last updated on May 11, 2020, 8:47 PM UTC (a7f27e6)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/immersive-web/webxr/1023/a64a328...asajeffrey:a7f27e6.html" title="Last updated on May 11, 2020, 8:47 PM UTC (a7f27e6)">Diff</a>
=> Made it explicit which realm each object gets created in

index.bs
The Editor's draft has some tightening up of language around realms, we should probably use it rather than the Level 1 spec.
***
<a href="https://pr-preview.s3.amazonaws.com/asajeffrey/webxr-spec/pull/1027.html" title="Last updated on May 11, 2020, 9:16 PM UTC (2b081f6)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/immersive-web/webxr/1027/a64a328...asajeffrey:2b081f6.html" title="Last updated on May 11, 2020, 9:16 PM UTC (2b081f6)">Diff</a>
=> Use the defn of invoking a callback from the ED of webidl

index.bs
`[=this=]` is only defined for methods/attributes/etc, so in the case of algorithms I just gave the object a name in the algorithm definition.
***
<a href="https://pr-preview.s3.amazonaws.com/Manishearth/webxr/pull/1028.html" title="Last updated on May 11, 2020, 9:19 PM UTC (42e1281)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/immersive-web/webxr/1028/8408e88...Manishearth:42e1281.html" title="Last updated on May 11, 2020, 9:19 PM UTC (42e1281)">Diff</a>
=> Use `this` instead of "target {{foo}}"

index.bs
Fixes #880
***
<a href="https://pr-preview.s3.amazonaws.com/Manishearth/webxr/pull/1031.html" title="Last updated on May 11, 2020, 10:03 PM UTC (fa56fc2)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/immersive-web/webxr/1031/f22797e...Manishearth:fa56fc2.html" title="Last updated on May 11, 2020, 10:03 PM UTC (fa56fc2)">Diff</a>
=> Short circuit updateRenderState() if no render state is passed

index.bs
fixes https://github.com/immersive-web/webxr/issues/1020, fixes https://github.com/immersive-web/webxr/issues/1022
I didn't update every instance of "queue a task" because both WebGL and HTML's Websocket section specify the task source used once in the document.
***
<a href="https://pr-preview.s3.amazonaws.com/Manishearth/webxr/pull/1032.html" title="Last updated on May 11, 2020, 10:13 PM UTC (17301e4)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/immersive-web/webxr/1032/f22797e...Manishearth:17301e4.html" title="Last updated on May 11, 2020, 10:13 PM UTC (17301e4)">Diff</a>
=> Cleanups on how we do tasks and promises

index.bs
Fixes #781.
Turns out most of the text was already there, I just added one more scenario and made sure they were clearly seen as examples rather than the only applicable situations.
***
<a href="https://pr-preview.s3.amazonaws.com/immersive-web/webxr/pull/1037.html" title="Last updated on May 12, 2020, 10:42 PM UTC (b99430f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/immersive-web/webxr/1037/b3a95eb...b99430f.html" title="Last updated on May 12, 2020, 10:42 PM UTC (b99430f)">Diff</a>
=> Minor change to when empty input profile arrays are appropriate.

index.bs
The definition of "transitory consent" already requires that the UI control that triggered the consent event must either be a descendant of the browsing context requesting the session, or a same-origin ancestor. So it's not obvious that the extra security checks are buying anything.
Fixes #873.
***
<a href="https://pr-preview.s3.amazonaws.com/asajeffrey/webxr-spec/pull/1030.html" title="Last updated on May 15, 2020, 4:56 PM UTC (1532f45)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/immersive-web/webxr/1030/26ffc6e...asajeffrey:1532f45.html" title="Last updated on May 15, 2020, 4:56 PM UTC (1532f45)">Diff</a>
=> Removed use of responsible and active and focused documents

index.bs
Fixes https://github.com/immersive-web/webxr/issues/1047
***
<a href="https://pr-preview.s3.amazonaws.com/Manishearth/webxr/pull/1048.html" title="Last updated on May 18, 2020, 8:27 PM UTC (3b2382d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/immersive-web/webxr/1048/d3aa05e...Manishearth:3b2382d.html" title="Last updated on May 18, 2020, 8:27 PM UTC (3b2382d)">Diff</a>
=> Mark correct paragraph as definition of 'view'

w3c.json
from https://github.com/immersive-web/dom-overlays/pull/31
are we better to remove shortname from w3c.json also??
=> updated w3c.json for current team contacts

index.bs
The `Note:` magic syntax doesn't work within lists
***
<a href="https://pr-preview.s3.amazonaws.com/Manishearth/webxr/pull/1059.html" title="Last updated on May 22, 2020, 10:12 PM UTC (51d7dd8)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/immersive-web/webxr/1059/58b5731...Manishearth:51d7dd8.html" title="Last updated on May 22, 2020, 10:12 PM UTC (51d7dd8)">Diff</a>
=> Properly style note

index.bs
fixes https://github.com/immersive-web/webxr/issues/363
also added another related note near the definition of immersive mode
***
<a href="https://pr-preview.s3.amazonaws.com/Manishearth/webxr/pull/1056.html" title="Last updated on May 20, 2020, 8:34 PM UTC (ea690e2)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/immersive-web/webxr/1056/071fe17...Manishearth:ea690e2.html" title="Last updated on May 20, 2020, 8:34 PM UTC (ea690e2)">Diff</a>
=> Clarify mouse behavior within immersive mode

index.bs
I don't see a clear reason why we're using signed integers (long in WebIDL) right now. My proposal would be to switch to unsigned ones.
***
<a href="https://pr-preview.s3.amazonaws.com/svillar/webxr/pull/1062.html" title="Last updated on May 25, 2020, 8:22 PM UTC (cd2ee6e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/immersive-web/webxr/1062/b86f723...svillar:cd2ee6e.html" title="Last updated on May 25, 2020, 8:22 PM UTC (cd2ee6e)">Diff</a>
=> Use unsigned long for rAF ids

index.bs
This change is needed to address https://github.com/immersive-web/layers/issues/143
Without this change, we can't patch the algorithm for sessions with layers.
***
<a href="https://pr-preview.s3.amazonaws.com/cabanier/webxr-1/pull/1064.html" title="Last updated on May 26, 2020, 5:26 PM UTC (d43de8e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/immersive-web/webxr/1064/b315c6b...cabanier:d43de8e.html" title="Last updated on May 26, 2020, 5:26 PM UTC (d43de8e)">Diff</a>
=> added 'check the layers state' algorithm

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/iBicha/webxr/pull/1066.html" title="Last updated on May 28, 2020, 9:19 PM UTC (db57980)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/immersive-web/webxr/1066/bedef88...iBicha:db57980.html" title="Last updated on May 28, 2020, 9:19 PM UTC (db57980)">Diff</a>
=> Fix depthFar in apply-pending-render-state

index.bs
This contains changes to:
- Allow poses to be null in more situations (fixes https://github.com/immersive-web/webxr/issues/1042)
- <s>Force emulation in `getViewerPose()`, making it not possible to return null poses, and delay `requestReferenceSpace()` until tracking has been established.</s> (https://github.com/immersive-web/webxr/issues/674)
- Reintroduce check for current global object in pose security check (removed in #1030)
- Make it so that the document visibility check can suppress poses without throwing an exception. Exceptions are for cases where the user's code is incorrect, not when stuff unpredictably changed from underneath the user. (partially addresses https://github.com/immersive-web/webxr/issues/1041)
- Some spec language cleanups around reference space creation
For …
=> Various changes around null and emulated poses

index.bs
In #1062 we moved from signed to unsigned integers in the return value of `requestAnimationFrame`. However we forgot to do the same for the cancelAnimationFrame() as it gets the handle returned by requestAnimationFrame().
***
<a href="https://pr-preview.s3.amazonaws.com/svillar/webxr/pull/1069.html" title="Last updated on May 29, 2020, 4:14 PM UTC (2a60982)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/immersive-web/webxr/1069/403f2e5...svillar:2a60982.html" title="Last updated on May 29, 2020, 4:14 PM UTC (2a60982)">Diff</a>
=> Use unsigned long for cancelAnimationFrame()

index.bs
I'm also open to removing it entirely, there seemed to be general consensus that `visibilityState` is enough.
Fixes #1041
***
<a href="https://pr-preview.s3.amazonaws.com/Manishearth/webxr/pull/1067.html" title="Last updated on May 29, 2020, 4:23 PM UTC (896e1ea)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/immersive-web/webxr/1067/403f2e5...Manishearth:896e1ea.html" title="Last updated on May 29, 2020, 4:23 PM UTC (896e1ea)">Diff</a>
=> Change document visibility check to be UA choice

index.bs
[`getViewerPose()`](https://immersive-web.github.io/webxr/#dom-xrframe-getviewerpose) step 3 will raise an `InvalidStateError` with input frames, so the line about views arrays being empty is meaningless since you can't create `XRViewerPose`s anyway.
fixes https://github.com/immersive-web/webxr/issues/1054
***
<a href="https://pr-preview.s3.amazonaws.com/Manishearth/webxr/pull/1053.html" title="Last updated on May 20, 2020, 6:05 PM UTC (b29755f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/immersive-web/webxr/1053/a059800...Manishearth:b29755f.html" title="Last updated on May 20, 2020, 6:05 PM UTC (b29755f)">Diff</a>
=> Mention correct input frame semantics on XRInputSource/frame

index.bs
This led to some confusion in https://github.com/immersive-web/anchors/issues/46.
Namely, native origins as a "type" are not some special tracked entity, rather, the object holding on to them has specal tracking behavior for updating them. Otherwise we are passing around types with spooky underspecified semantics.
This also corrects how origin offsets work, there is no point in copying the native origin, it's the _type_ which must be copied.
***
<a href="https://pr-preview.s3.amazonaws.com/Manishearth/webxr/pull/1071.html" title="Last updated on Jun 2, 2020, 1:06 AM UTC (0b1b51a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/immersive-web/webxr/1071/efa3f25...Manishearth:0b1b51a.html" title="Last updated on Jun 2, 2020, 1:06 AM UTC (0b1b51a)">Diff</a>
=> Clarify some things about native origins

index.bs
This fixes #1036 by making sure "ensure an immersive device is selected" is only called in parallel, and deprecating `xrCompatible` due to slow sync behavior.
This fixes #1044 by specifying the behavior of the flag the same way WebGL does, as opposed to patching the HTML spec.
=> Clarify threading nature of "ensure an immersive device is selected", deprecate xrCompatible

index.bs
Alternate to  #1080
This PR adds an additional-views feature that can be used as a hint that the content is expecting additional views.
Related: immersive-web/webxr-ar-module#57
Fixes #1045
=> Add feature for secondary views

README.md
Added the CG spec repos to readme. Let me know if I am missing anything or want to add it somewhere else instead.
=> Add CG specs links

index.bs
Fixes #1010 
Second attempt at https://github.com/immersive-web/webxr/pull/1086
This PR only caches:
- XRViewport obejcts when the viewport has not changed
- XRFrame objects for animation frames
We determined that caching poses is probably too dangerous since they're "plain old data" types that folks may choose to hold on to. Leaving #1086 as a separate PR if people are interested in seeing how that would work.
cc @asajeffrey @MortimerGoro @cabanier
***
<a href="https://pr-preview.s3.amazonaws.com/Manishearth/webxr/pull/1088.html" title="Last updated on Jun 26, 2020, 5:06 PM UTC (deb6236)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/immersive-web/webxr/1088/9106241...Manishearth:deb6236.html" title="Last updated on Jun 26, 2020, 5:06 PM UTC (deb6236)">Diff</a>
=> Allow caching various objects (take 2)

index.bs
Fixes https://github.com/immersive-web/webxr/issues/1090
Also fixes https://github.com/immersive-web/webxr/issues/1092 by adding a timestamp comparison.
***
<a href="https://pr-preview.s3.amazonaws.com/Manishearth/webxr/pull/1093.html" title="Last updated on Jun 30, 2020, 10:35 PM UTC (4e1bb2e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/immersive-web/webxr/1093/e07923f...Manishearth:4e1bb2e.html" title="Last updated on Jun 30, 2020, 10:35 PM UTC (4e1bb2e)">Diff</a>
=> Fixup frame and viewport caching to be explicit

index.bs
This explicitly draws a distinction between active and inactive views, so that the list of views and viewports becomes immutable.
Fixes https://github.com/immersive-web/webxr/issues/1094#issuecomment-653160394
Needed for https://github.com/immersive-web/layers/issues/180#issuecomment-653160676
cc @asajeffrey @cabanier
***
<a href="https://pr-preview.s3.amazonaws.com/Manishearth/webxr/pull/1096.html" title="Last updated on Jul 6, 2020, 8:16 PM UTC (8fad461)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/immersive-web/webxr/1096/d01049d...Manishearth:8fad461.html" title="Last updated on Jul 6, 2020, 8:16 PM UTC (8fad461)">Diff</a>
=> Introduce concept of active view

index.bs
Fixes #1051. Would love @asajeffrey's input on this!
Apologies that this has taken as long as it has to get a PR up. Doing some GH and meeting minutes archeology, the primary concerns about the algorithm as it currently is written seem to be that Alan needs it to allow for non-blocking communication to the XR hardware and otherwise myself and a couple of others just want to ensure that the timing of when the changes apply is reasonably predictable.
This change moves the  `apply the pending render state` execution to immediately after the frame loop executes, and queues a task to do it. Then it also moves the execution of the frame loop into a task on the same queue, which _should_ implicitly ensure that the render state update must finish before the next frame executes. (I believe that …
=> Change timing of when updateRenderState changes apply

index.bs
Purely an aesthetic choice. I find this far more pleasant to read in bikeshed form, and it doesn't change the rendering (aside from a few inexplicable pixel shifts.)
***
<a href="https://pr-preview.s3.amazonaws.com/immersive-web/webxr/pull/1125.html" title="Last updated on Sep 14, 2020, 10:50 PM UTC (527e1ef)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/immersive-web/webxr/1125/e27913c...527e1ef.html" title="Last updated on Sep 14, 2020, 10:50 PM UTC (527e1ef)">Diff</a>
=> Switch over to use the newer (and more readable) bikeshed switch syntax

index.bs
Fixes #1123
***
<a href="https://pr-preview.s3.amazonaws.com/Manishearth/webxr/pull/1126.html" title="Last updated on Sep 16, 2020, 6:49 PM UTC (199fbef)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/immersive-web/webxr/1126/ef91f05...Manishearth:199fbef.html" title="Last updated on Sep 16, 2020, 6:49 PM UTC (199fbef)">Diff</a>
=> Gate context XR compatability on xr-spatial-tracking permissions policy.

index.bs
Fixes #1127
This change allows the `apply the pending render state` algorithm to run even when the current layer state is invalid.
***
<a href="https://pr-preview.s3.amazonaws.com/immersive-web/webxr/pull/1128.html" title="Last updated on Sep 17, 2020, 5:49 PM UTC (afe353b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/immersive-web/webxr/1128/bc96697...afe353b.html" title="Last updated on Sep 17, 2020, 5:49 PM UTC (afe353b)">Diff</a>
=> Ensure that pending render state is always applied.

index.bs
Making use of a trick I learned in the WebGPU spec to allow more concise expression of code literals.
Mostly because I really hate both reading and writing `<code></code>` over and over again. 😉
***
<a href="https://pr-preview.s3.amazonaws.com/immersive-web/webxr/pull/1130.html" title="Last updated on Sep 18, 2020, 4:36 PM UTC (effd87c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/immersive-web/webxr/1130/1383923...effd87c.html" title="Last updated on Sep 18, 2020, 4:36 PM UTC (effd87c)">Diff</a>
=> Make use of markdown syntax to clean up <code> tags

index.bs
This clarification was requested as part of the dynamic viewport scaling discussion, see https://github.com/immersive-web/webxr/issues/1091#issuecomment-672250898 .
***
<a href="https://pr-preview.s3.amazonaws.com/klausw/webxr/pull/1131.html" title="Last updated on Sep 23, 2020, 12:58 AM UTC (bdd3223)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/immersive-web/webxr/1131/ea307eb...klausw:bdd3223.html" title="Last updated on Sep 23, 2020, 12:58 AM UTC (bdd3223)">Diff</a>
=> Clarify that framebuffer scale factors apply to width/height separately

index.bs
See https://github.com/immersive-web/webxr/issues/1091
***
<a href="https://pr-preview.s3.amazonaws.com/klausw/webxr/pull/1132.html" title="Last updated on Sep 24, 2020, 11:18 PM UTC (634e8cf)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/immersive-web/webxr/1132/ea307eb...klausw:634e8cf.html" title="Last updated on Sep 24, 2020, 11:18 PM UTC (634e8cf)">Diff</a>
=> Add requestViewportScale/recommendedViewportScale

Makefile, index.bs
(Hopefully) Fixes #983
Tried to capture some of the conclusions we came to on the most recent call regarding fingerprinting here. I suspect it'll need some iteration, and I'm very happy to take feedback! The high level points I'm trying to communicate:
- In situations where XR is ~always supported (Oculus browser, for example) returning true without further checks is fine.
- Same goes for situations where XR is never supported, for obvious reasons.
- Systems with highly variable support (ie: XR as a peripheral) represent the highest fingerprinting risk and should determine user intent before advertising. Exactly how that happens is left to the UA.
***
<a href="https://pr-preview.s3.amazonaws.com/immersive-web/webxr/pull/1124.html" title="Last updated on Oct 14, 2020, 6:54 PM UTC …
=> Incorporating conclusions of recent privacy discussions

index.bs
Fixes any leftover issues from https://github.com/immersive-web/webxr/pull/1124
After discussion with @pes10k and @toji , we've decided that the best path forward is to keep the normative part of the spec simple and move the pref autogranting to a separate non normative section.
(We should probably move this into the "fingerprinting" section at the bottom of the spec, but that also needs some cleanup)
***
<a href="https://pr-preview.s3.amazonaws.com/Manishearth/webxr/pull/1146.html" title="Last updated on Dec 2, 2020, 1:33 AM UTC (f793a82)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/immersive-web/webxr/1146/62a3c1f...Manishearth:f793a82.html" title="Last updated on Dec 2, 2020, 1:33 AM UTC (f793a82)">Diff</a>
=> Make sessionsupported pref autogranting non-normative

index.bs
This stabilizes the last unstable section of the spec, one of the CR blockers. It does not seem to me that the contents of these sections are still up for debate, though we should probably check in with the group.
This also moves the `isSessionSupported()` fingerprinting section to the privacy/security section, now that the main fingerprinting section is stable.
***
<a href="https://pr-preview.s3.amazonaws.com/Manishearth/webxr/pull/1153.html" title="Last updated on Dec 27, 2020, 7:41 PM UTC (b660c1f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/immersive-web/webxr/1153/9edd25f...Manishearth:b660c1f.html" title="Last updated on Dec 27, 2020, 7:41 PM UTC (b660c1f)">Diff</a>
=> Mark context isolation/fingerprinting sections as stable, reorganize

index.bs
This is intended to avoid exposing detailed performance or GPU
utilization data during the session.
***
<a href="https://pr-preview.s3.amazonaws.com/klausw/webxr/pull/1151.html" title="Last updated on Dec 16, 2020, 9:52 PM UTC (1a7047d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/immersive-web/webxr/1151/9edd25f...klausw:1a7047d.html" title="Last updated on Dec 16, 2020, 9:52 PM UTC (1a7047d)">Diff</a>
=> Require quantization for recommendedViewportScale

index.bs
Other specs (depth sensing API, layers) rely or will rely on being able
to obtain XRFrame instance from an XRView. At a first glance, this
change should be safe to make, but please let me know if I am missing
something here and there was a reason not to put XRFrame on an XRView
other than "no-one needed it before".
One algorithm was also changed to compare XRFrame instances - this is
not required and we could keep comparing frame times there if people
prefer that.
Misc. change: fix one linking error for getNativeFramebufferScaleFactor.
***
<a href="https://pr-preview.s3.amazonaws.com/bialpio/webxr/pull/1165.html" title="Last updated on Jan 26, 2021, 9:56 PM UTC (c0addfc)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/immersive-web/webxr/1165/022c516...bialpio:c0addfc.html" …
=> Add associated XRFrame to XRView, remove frame time

index.bs
Fixes #1166, matches implemented behavior in browsers.
***
<a href="https://pr-preview.s3.amazonaws.com/immersive-web/webxr/pull/1170.html" title="Last updated on Feb 5, 2021, 5:41 PM UTC (6f533e3)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/immersive-web/webxr/1170/ffe5171...6f533e3.html" title="Last updated on Feb 5, 2021, 5:41 PM UTC (6f533e3)">Diff</a>
=> Reject promise returned from end() if session is already ended

index.bs
Fixes #1171
The fact that this was phrased as "disabled" was a historical artifact left over from a point when the flag was going to be exposed as part of the API surface and we wanted it to default to `false`.
***
<a href="https://pr-preview.s3.amazonaws.com/immersive-web/webxr/pull/1172.html" title="Last updated on Feb 8, 2021, 6:55 PM UTC (9b06b86)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/immersive-web/webxr/1172/c3878b0...9b06b86.html" title="Last updated on Feb 8, 2021, 6:55 PM UTC (9b06b86)">Diff</a>
=> Inverted composition disabled flag to be composition enabled

index.bs
Closes #619
Also silences a couple of bikeshed warnings.
***
<a href="https://pr-preview.s3.amazonaws.com/cabanier/webxr/pull/1182.html" title="Last updated on Mar 13, 2021, 4:42 AM UTC (fb091a2)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/immersive-web/webxr/1182/39aad3f...cabanier:fb091a2.html" title="Last updated on Mar 13, 2021, 4:42 AM UTC (fb091a2)">Diff</a>
=> Added support for angular and linear velocity

index.bs
Also fixed up `origin` links
***
<a href="https://pr-preview.s3.amazonaws.com/cabanier/webxr/pull/1184.html" title="Last updated on Mar 21, 2021, 12:31 AM UTC (44afdbf)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/immersive-web/webxr/1184/10a4f07...cabanier:44afdbf.html" title="Last updated on Mar 21, 2021, 12:31 AM UTC (44afdbf)">Diff</a>
=> Added note about user intent with web applications

.gitignore
to prevent events similar to https://github.com/immersive-web/webxr/pull/1184#pullrequestreview-616972241
(do we need to keep node/npm related lines used(??) for TravisCI?)
=> added index.html to .gitignore

index.bs
Previously, features would "carry over" between XR sessions for the same web page, which can lead to sessions unpredictably being granted features they did not ask for.
With this change, sessions may only use features they have explicitly requested. Previously granted features are still used to skip consent prompts, but must be explicitly requested on session creation.
Note: prior to this PR, the experimental not-yet-implemented [Permissions Request](https://wicg.github.io/permissions-request/) API could have been used for mid session feature requests. That is no longer the case and we need to add an API to reenable this if we wish (https://github.com/immersive-web/webxr/issues/1190).
Fixes #1178
***
<a href="https://pr-preview.s3.amazonaws.com/immersive-web/webxr/pull/1189.html" …
=> Only allow sessions to use features they explicity request or are implicitly granted based on mode

index.bs
Fix reference to XR device's set of granted features - bikeshed by default seems to pick the one belonging to XRSession (clicking on https://immersive-web.github.io/webxr/#xrsession-set-of-granted-features shows a link to section 14.2, and takes me to this algorithm step).
***
<a href="https://pr-preview.s3.amazonaws.com/bialpio/webxr/pull/1204.html" title="Last updated on Jun 17, 2021, 9:13 PM UTC (da0f566)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/immersive-web/webxr/1204/cbd417a...bialpio:da0f566.html" title="Last updated on Jun 17, 2021, 9:13 PM UTC (da0f566)">Diff</a>
=> Fix ref. to XR device's set of granted features

index.bs
we currently don't have level for webxr spec, Level line should point none instead of 1
***
<a href="https://pr-preview.s3.amazonaws.com/himorin/webxr/pull/1218.html" title="Last updated on Aug 24, 2021, 4:15 PM UTC (99fc03b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/immersive-web/webxr/1218/b1b191f...himorin:99fc03b.html" title="Last updated on Aug 24, 2021, 4:15 PM UTC (99fc03b)">Diff</a>
=> fix for WD 20210824

index.bs
as https://github.com/immersive-web/webxr/pull/1224 (forgot one additional line)
***
<a href="https://pr-preview.s3.amazonaws.com/himorin/webxr/pull/1229.html" title="Last updated on Sep 30, 2021, 6:54 AM UTC (979b897)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/immersive-web/webxr/1229/b5892f0...himorin:979b897.html" title="Last updated on Sep 30, 2021, 6:54 AM UTC (979b897)">Diff</a>
=> fixed link in header (forgot one)

index.bs
Hi everyone,
Following up on #1211 and the discussion in the latest meeting, here's a proposal/draft for the `XRFrame.predictedDisplayTime` property.
I adapted the main loop rendering example to demonstrate the use of `predictedDisplayTime`. While the explicit time parameter here is redundant, it shows a clear difference to the window rAF.
This spec currently expects the implementor to understand how the display time could be predicted rather than providing an algorithm. I'm uncertain if it is okay to assume that the underlying implementation/SDK has this value available (as discussed, [it is for OpenXR](https://www.khronos.org/registry/OpenXR/specs/1.0/man/html/openxr.html#XrFrameState)). Could it be useful to add a suggestion for what to set the value to if it is not?
Best,
Jonathan
*** …
=> Add XRFrame.predictedDisplayTime

index.bs
***
[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Oct 5, 2021, 8:44 PM UTC)_.
<details>
<summary>More</summary>
PR Preview relies on a number of web services to run. There seems to be an issue with the following one:
:rotating_light: [HTML Diff Service](http://services.w3.org/htmldiff) - The HTML Diff Service is used to create HTML diffs of the spec changes suggested in a pull request.
:link: [Related URL](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fpr-preview.s3.amazonaws.com%2Fimmersive-web%2Fwebxr%2Fpull%2F1230%2Fcc6b625.html&doc2=https%3A%2F%2Fpr-preview.s3.amazonaws.com%2Fcabanier%2Fwebxr%2Fpull%2F1230.html)
```
<html><body><h1>503 Service Unavailable</h1>
No server is available to handle this request.
</body></html>
```
_If you …
=> Fixed up predictedDisplayTime + defined inline behavior

README.md
(wondered whether to keep current incomplete? list of specs, but considering maintainability, just replaced - as an idea at the first moment)
Replaced list of specs in README, with a link to list_spec page.
=> replaced list of specs in IWWG/IWCG to a link to list_spec page

explainer.md
Name of the section was different
=> Fix cross ref link in toc

images/rigid_matrix.svg, images/rotation_matrix.svg, images/translation_matrix.svg, index.bs
bikeshed does not pick image size for SVG (see also: https://github.com/tabatkins/bikeshed/issues/2042)
This PR copies height attribute from SVG images into source.
***
<a href="https://pr-preview.s3.amazonaws.com/himorin/webxr/pull/1246.html" title="Last updated on Dec 24, 2021, 5:47 AM UTC (e5e10b4)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/immersive-web/webxr/1246/08e6fab...himorin:e5e10b4.html" title="Last updated on Dec 24, 2021, 5:47 AM UTC (e5e10b4)">Diff</a>
=> [editorial] copy SVG height into img

index.bs
fixed for syntax and linking errors.
***
[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Mar 25, 2022, 9:36 AM UTC)_.
<details>
<summary>More</summary>
PR Preview relies on a number of web services to run. There seems to be an issue with the following one:
:rotating_light: [CSS Spec Preprocessor](https://api.csswg.org/bikeshed/) - CSS Spec Preprocessor is the web service used to build Bikeshed specs.
:link: [Related URL](https://api.csswg.org/bikeshed/?url=https%3A%2F%2Fraw.githubusercontent.com%2Fimmersive-web%2Fwebxr%2F692e0001a8719beef46207bce70fe1dc9d6d4b51%2Findex.bs&force=1&md-warning=not%20ready)
```
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>500 Internal Server Error</title>
</head><body>
<h1>Internal Server …
```
=> before-CR fixed syntax

index.bs
Fixes #1258
following the guidance at whatwg/html#7694
***
<a href="https://pr-preview.s3.amazonaws.com/Manishearth/webxr/pull/1268.html" title="Last updated on Mar 30, 2022, 4:35 PM UTC (cb22638)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/immersive-web/webxr/1268/e731e1b...Manishearth:cb22638.html" title="Last updated on Mar 30, 2022, 4:35 PM UTC (cb22638)">Diff</a>
=> Replace use of responsible document

index.bs
Per Issue #1205, this proposal makes the following changes:
1) Exposes the XRSession's set of granted features as a FrozenArray attribute `enabledFeatures`
2) Requires feature descriptors to be represented by DOMStrings, with any additional initialization being added as an extended member on XRSessionInit.
Note that this second change is consistent with how feature descriptors have currently been extended by the various other specs. It essentially requires that we have a string representation of the feature and can then further configure the feature as needed.
***
<a href="https://pr-preview.s3.amazonaws.com/alcooper91/webxr/pull/1296.html" title="Last updated on Aug 17, 2022, 8:43 PM UTC (8ac6957)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/immersive-web/webxr/1296/f675669 …
=> Expose XRSession's granted features

explainer.md
Updates the explainer to make use of the enabledFeatures attribute rather than needing to request and have the promise reject.
=> Update explainer to more idiomatic feature detection

index.bs
The "poses may be reported" algorithm previously indicated that poses could only be reported if the visibility state was "visible", but that appears to be a mistake originating from the fact that "visible-blurred" was added later. The description of "visible-blurred" mentioned throttled head poses, so obviously the intention was to allow some poses in that state, just not input poses.
This change alters the "poses may be reported" algorithm to only suppress poses when the visiblity state is "hidden", and adds an explicit step to the "populate the pose" algorithm that prevents input poses from being returned if the visibility state is "visible-blurred"
Thanks @AdaRoseCannon for pointing this out!
***
<a href="https://pr-preview.s3.amazonaws.com/immersive-web/webxr/pull/1332.html" …
=> Clarify getPose behavior with visibile-blurred

index.bs
This PR is to give explicit allowances for operating systems to show things for user safety or comfort which either punch through or are show on top of the XR scene.
Examples are if the user doesn't request hands in WebXR but there is no other input then it's more comfortable if the OS shows something.
***
<a href="https://pr-preview.s3.amazonaws.com/AdaRoseCannon/webxr/pull/1344.html" title="Last updated on Aug 31, 2023, 7:16 PM UTC (75e7044)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/immersive-web/webxr/1344/98e6946...AdaRoseCannon:75e7044.html" title="Last updated on Aug 31, 2023, 7:16 PM UTC (75e7044)">Diff</a>
=> Add allowance for system ui for safety

index.bs
Similar changes to https://github.com/immersive-web/layers/pull/305
***
<a href="https://pr-preview.s3.amazonaws.com/cabanier/webxr/pull/1359.html" title="Last updated on Feb 8, 2024, 11:26 PM UTC (656e17e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/immersive-web/webxr/1359/47d14b6...cabanier:656e17e.html" title="Last updated on Feb 8, 2024, 11:26 PM UTC (656e17e)">Diff</a>
=> Clarify rgb vs srgb behavior

index.bs
[Page Visibility Level 2](https://www.w3.org/TR/2022/DISC-page-visibility-2-20220623/) had discontinued at 2022-06-23.
Refer `[=Document/visibilityState=]` instead.
***
<a href="https://pr-preview.s3.amazonaws.com/himorin/webxr/pull/1373.html" title="Last updated on Jul 1, 2024, 5:24 PM UTC (e79908d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/immersive-web/webxr/1373/3dec73d...himorin:e79908d.html" title="Last updated on Jul 1, 2024, 5:24 PM UTC (e79908d)">Diff</a>
=> Replace PAGE-VISIBILITY-2 with WHATWG/HTML

index.bs
added a list of normative changes' PRs (see details in mail)
***
<a href="https://pr-preview.s3.amazonaws.com/himorin/webxr/pull/1374.html" title="Last updated on Jul 4, 2024, 12:27 PM UTC (0b9567e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/immersive-web/webxr/1374/05f9a35...himorin:0b9567e.html" title="Last updated on Jul 4, 2024, 12:27 PM UTC (0b9567e)">Diff</a>
=> Changelog from CRS1

input-explainer.md
This is a bit inconsistent right now, fixing here since I assume the spec is up-to-date:
https://www.w3.org/TR/webxr/#xrinputsourceschangeevent-interface
=> Fix: incorrect type name `XRInputSourceChangeEvent` renamed `XRInputSourcesChangeEvent` as per spec

index.bs
This algorithm can now handle the need to report an exception inside an XR animation frame callback.
Part of whatwg/webidl#1425.
***
<a href="https://pr-preview.s3.amazonaws.com/jeremyroman/webxr/pull/1380.html" title="Last updated on Aug 2, 2024, 6:42 PM UTC (e4afebb)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/immersive-web/webxr/1380/c43a518...jeremyroman:e4afebb.html" title="Last updated on Aug 2, 2024, 6:42 PM UTC (e4afebb)">Diff</a>
=> Editorial: Update use of WebIDL "invoke a callback function"

index.bs
Per [WebIDL spec](https://webidl.spec.whatwg.org/#SameObject), 
> The [SameObject] extended attribute must not be used on anything other than a read only attribute whose type is an interface type or object.
`skipRendering` is a boolean, so it isn't eligible. Encountered while updating Servo and getting an error during codegen
***
<a href="https://pr-preview.s3.amazonaws.com/msub2/webxr/pull/1382.html" title="Last updated on Aug 21, 2024, 6:37 AM UTC (62c3177)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/immersive-web/webxr/1382/f25c42f...msub2:62c3177.html" title="Last updated on Aug 21, 2024, 6:37 AM UTC (62c3177)">Diff</a>
=> Remove SameObject attribute from skipRendering

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/cabanier/webxr/pull/1361.html" title="Last updated on Oct 21, 2024, 3:21 PM UTC (daa8a66)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/immersive-web/webxr/1361/656e17e...cabanier:daa8a66.html" title="Last updated on Oct 21, 2024, 3:21 PM UTC (daa8a66)">Diff</a>
=> First pass at defining tracked sources

index.bs
Just a small typo fix
***
<a href="https://pr-preview.s3.amazonaws.com/msub2/webxr/pull/1406.html" title="Last updated on Mar 26, 2025, 1:38 AM UTC (37c941e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/immersive-web/webxr/1406/90be248...msub2:37c941e.html" title="Last updated on Mar 26, 2025, 1:38 AM UTC (37c941e)">Diff</a>
=> pasthrough -> passthrough

index.bs
The other immersive web specs have a mix of trying to link to [=XRSession/ended=] or simply [=ended=]. However, when they link to [=ended=], they can link to arbitrary specs that also define this term. I was unable to determine how to import our explicit version of [=ended=]. However, this really should be exported as an attribute of the item. While this will leave a handful of our dependent specs still with broken links, it should fix the others.
***
<a href="https://pr-preview.s3.amazonaws.com/immersive-web/webxr/pull/1407.html" title="Last updated on Apr 16, 2025, 5:41 PM UTC (9a33c0a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/immersive-web/webxr/1407/108c57c...9a33c0a.html" title="Last updated on Apr 16, 2025, 5:41 PM UTC (9a33c0a)">Diff</a>
=> Editorial: Fix XRSession/ended links

index.bs
@toji suggested using a [mixin](https://webidl.spec.whatwg.org/#idl-interface-mixins) as the editorial concept we discussed in the latest IWWG call. I quickly tested this in Chrome and it doesn't seem to trigger any unexpected web-observable changes. 
However, when I run the spec through https://api.csswg.org/bikeshed/ after my changes, I see:
```
WARNING: Skipped generating some MDN panels, because the following IDs weren't present in the document. Use `Ignore MDN Failure` if this is expected.
#dom-xrview-projectionmatrix
#dom-xrview-transform
```
Not sure what if anything needs to be done to resolve this, but I welcome any insights
***
<a href="https://pr-preview.s3.amazonaws.com/immersive-web/webxr/pull/1408.html" title="Last updated on Apr 17, 2025, 6:24 PM UTC (289445c)">Preview</a> …
=> Introduce XRViewGeometry mixin concept
